### ISSUE TITLE
How to serialize from a relationship?

### ISSUE THREAD

**Issue by mikkergimenez** [neo4j-contrib/neomodel#145]
Hello,
   I am looking at this example:

germany = Country(code='DE').save()
jim.country.connect(germany)

if jim.country.is_connected(germany):
    print("Jim's from Germany")

for p in germany.inhabitant.all()

and I'm trying to serialize germany.inhabitant or germany.inhabitant.all() to return as json or a list->json in my view but can't.

I've tried p.get_properties() per py2neo, and various other list() dict() values and even django's built in serializer, but no dice.

Any thoughts?  I think I've seen one example that involves just manually creating each list

list['key'] = p.key

and on down the list, but that won't work for me as my key's are quite variable.

**Comment by HashRocketSyntax** [comment]
Once you have a `dict` dump it to json
