### ISSUE TITLE
Use Nodeset with query result?

### ISSUE THREAD

**Issue by mjmare** [neo4j-contrib/neomodel#232]
Nodeset provides useful filtering functions. Would it be possible to use Nodeset with a list of nodes (Neomodel nodes) obtained with, say, a cypher query?

It would be useful to document how a Nodeset is created.

**Comment by robinedwards** [comment]
There is some documentation for nodeset but not on actually creating
instances. It was kind of designed as something the neomodel api produces
for you.

Having said that i can see use cases for starting from a bunch of nodes
retrieved directly through cypher then producing a nodeset to query further.

Could you perhaps give me example of how you see it working or what you are
trying to achieve.

**Comment by mjmare** [comment]
My usecase today was a situation where I had a cypher query that returned a list of nodes. Subsequently I'd like to do some adhoc filtering and sorting (since the data has s displayed in a table), for which a Nodeset seemed like just the thing.

**Comment by robinedwards** [comment]
Cool i will try and come up with something.

**Comment by funkyfuture** [comment]
similarily i'd like to `Model.nodes.all().order_by('some_property')`.
