### ISSUE TITLE
Support for Bookmarking used by Causal Clustering

### ISSUE THREAD

**Issue by akgoel-mo** [neo4j-contrib/neomodel#257]
We have a production causal cluster, which is experiencing data inconsistencies. Upon research, we found that we need to depend on a bookmark which ensures causal consistency.

I noticed that neo4j-python-driver already has support for bookmarking, but the same is not being used by neomodel yet. Is there any plan to handle bookmarks inside neomodel, in near future?

**Comment by akgoel-mo** [comment]
Adding my colleague to stay updated with the issue - @mshekhar-mE

**Comment by robinedwards** [comment]
Hey, no there isn't at present but I would gladly accept any PR's adding support for it

**Comment by akgoel-mo** [comment]
We are looking at adding the support soon, to our fork, and will also provide a PR to the base, for the same. I cant ensure a timeline on this yet, but we certainly need this soon. For now, we are trying to find workarounds on this, to fix the issue at hand. Once done, we will plan for this implementation.

We might need some support from you as well, to understand the existing code and any guidelines you have setup, to contribute to the core neomodel. Any pointers/ideas you have that might make the implementation simpler/smoother for us, are happily welcome.

**Comment by akgoel-mo** [comment]
@robinedwards Can you check the above PR?

**Comment by robinedwards** [comment]
Sounds great.

Guidelines wise not much, just try to conform to PEP8 where possible, always supply docs and tests :-)

**Comment by aanastasiou** [comment]
@akgoel-mo Any update on this?

**Comment by akgoel-mo** [comment]
Hi @aanastasiou 

We did get the routing support added in this PR - https://github.com/neo4j-contrib/neomodel/pull/264

As for the bookmarking support, it moved down on our list of priorities. As such we weren't able to get it through at our end.

Sorry about that.

**Comment by aanastasiou** [comment]
Hi @akgoel-mo 

Thank you very much for such a quick response. Yes, I noticed 264.

No worries about bookmarking support, I will mark this as a feature anyway and see if anything could be done in an upcoming version.

All the best

**Comment by kupuguy** [comment]
I've submitted a PR that adds bookmarking support.

See https://github.com/neo4j-contrib/neomodel/blob/62dc06d116703b0ed3cab737db488214ac0fdd0c/doc/source/transactions.rst for documentation: it works with decorators, context managers, and explicit `db.begin()...db.commit()`. 

https://github.com/neo4j-contrib/neomodel/pull/478

**Comment by AntonLydike** [comment]
I'll close this issue, I think everything was merged? Feel free to re-open if you think something was missed!
