### ISSUE TITLE
Differentiating between From and To Relationships

### ISSUE THREAD

**Issue by aaronst** [neo4j-contrib/neomodel#266]
For any given node, we can get a list of relationships with `__all_relationships__`.  However, I'm not seeing a way to differentiating between relationships (`RelationshipTo`) and reverse relationships (`RelationshipFrom`).  I thought maybe I could inspect the `source` or `source_class` property on each of the relationships but, even for reverse relationships, it is the node where the relationship is defined.  It would be nice to be able to programmatically differentiate `RelationshipTo`s and `RelationshipFrom`s.

**Comment by aanastasiou** [comment]
@aaronst Relationships TO a node have a `direction` attribute in their `definition`  of 1 while relationships FROM have a `direction` attribute of -1.

Therefore, you can always:

```
all_rels_to = list(filter(lambda x:x[1].definition["direction"]==1,SomeNeomodelClass.__all_relationships__))
all_rels_from = list(filter(lambda x:x[1].definition["direction"]==-1,SomeNeomodelClass.__all_relationships__))
```

Which is one step "deeper" than splitting the `RelationshipDefinition` in two classes that explicitly set their `definition`'s direction to the right value which would allow you to `filter` on `isinstance`.

What do you think?
