### ISSUE TITLE
convert datetime.datetime

### ISSUE THREAD

**Issue by trojek** [neo4j-contrib/neomodel#269]
In my model class, I have a field which is `datetime` type. When I get information about the node the field looks like:
`datetime.datetime(2017, 9, 19, 9, 22, 3, 287144, tzinfo=<UTC>)`
Is there exist any method to convert it into something like: `2000-01-01 00:00:00` or timestamp in ms?

**Comment by robinedwards** [comment]
Yes please see the docs for pythons datetime module
