### ISSUE TITLE
Advanced queries - current state / documentation

### ISSUE THREAD

**Issue by trojek** [neo4j-contrib/neomodel#271]
As far as I understand Neomodel doesn't support "advanced" queries (e.g. filter by related model). Is there exist documentation which shows what is covered in Neomodel in relation to neo4j Cypher?

I think that it would be helpful both for people how wants to use Neomodel in their project and people who want to add missing functions to the Neomodel.

**Comment by aanastasiou** [comment]
Has [this](https://neomodel.readthedocs.io/en/latest/queries.html) been any better (since Sep 2017) ?
