### ISSUE TITLE
cardinality declaration on RelationshipFrom does not work as expected

### ISSUE THREAD

**Issue by elferia** [neo4j-contrib/neomodel#275]
According to the document, you can declare cardinality as an argument of `RelationshipFrom`.
```python
class Car(StructuredNode):
    owner = RelationshipFrom('Person', 'CAR', cardinality=One)
```

This code can be interpreted that "a car is owned by exactly one person."
But the following code does not fail:
```python
p1 = Person().save()
p2 = Person().save()
c = Car().save()
p1.car.connect(c)
p2.car.connect(c)  # a car is owned by 2 people?
```

As I asked in #274 , does cardinality declaration on `RelationshipFrom` do nothing?

**Comment by robinedwards** [comment]
It prevents you from connecting multiple persons to the car. I.e it
protects violations done via the object the constraint is called on.

So you need to also declare it on person for it to be fully enforced.

**Comment by elferia** [comment]
> it protects violations done via the object the constraint is called on.

I understood this by writing some tests.
```python
class Person(StructuredNode):
    car = RelationshipTo('Car', 'CAR', cardinality=One)


class Car(StructuredNode):
    owner = RelationshipFrom('Person', 'CAR', cardinality=One)


class CardinalityTest(TestCase):
    @raises(AttemptedCardinalityViolation)
    def test_car_cannot_owned_by_2_person_connected_from_person(self):
        jim = Person().save()
        car = Car().save()
        jim.car.connect(car)
        bob = Person().save()
        bob.car.connect(car)  # does not raise AttemptedCardinalityViolation because cardinality checking works on the connect()ing node bob, so this test fails

    @raises(AttemptedCardinalityViolation)
    def test_car_cannot_owned_by_2_person_connected_from_car(self):
        jim = Person().save()
        car = Car().save()
        car.owner.connect(jim)
        bob = Person().save()
        car.owner.connect(bob)  # raises AttemptedCardinalityViolation because cardinality checking works on the connect()ing node car, so this test passes
```

In conclusion, when connecting `Person` and `Car`, we cannot check both that the `Person` owns only the `Car` and that the `Car` is owned by only the `Person`. Is this right?

By the way, [code in document about cardinality](http://neomodel.readthedocs.io/en/latest/relationships.html) is wrong.
> class Car(StructuredNode):
>     owner = RelationshipFrom('Person', cardinality=One)

`RelationshipFrom()` lacks 2nd positional argument that specifies the label of relation.

**Comment by aanastasiou** [comment]
[Related](https://github.com/neo4j-contrib/neomodel/issues/282).

The bit about the documentation seems to have been taken care of by now.
