### ISSUE TITLE
db.set_connection does not work in (pyramid) web app

### ISSUE THREAD

**Issue by mjmare** [neo4j-contrib/neomodel#278]
At web app setup I set the connection URL with db.set_connection('bolt://neo4j:blabla@localhost:7687'). However when Neomodel models are accessed in a (pyramid) view the credentials are not set (as verified in debugger; they are reset to the default neo4j:neo4j). The same holds for direct queries with db.cypher_query(...).
When I resorted to using config.DATABASE_URL things work again. 

So it seems that the connection details set with db.set_connection are ephemeral in web app threads. Maybe this is by design, maybe not. If the former it might be mentioned in the docs.

**Comment by aanastasiou** [comment]
@mjmare Does this work as expected in `3.3.1` (?)
