### ISSUE TITLE
Property with leading underscore and independent database property name is not written to database

### ISSUE THREAD

**Issue by mjmare** [neo4j-contrib/neomodel#279]
I wanted to have a read-only property that would be written to the database but set when setting another property. 
```
class FileNode(BaseNode):
    file_id = StringProperty(db_property='content')
    _content_type = StringProperty(db_property='content_type')
    :
    (getter and setter for content)
    (getter for content_type)

```
When using this Node type the content property would be set by the user (through the setter) and the content_type derived in that process.

All went well except that the value for the content_type was not present in the node in the database. 
It turn out that changing *_content_type* to *content_type_* fixes it. 
So properties with a leading underscore seem to be ignored, which was unexpected.

**Comment by robinedwards** [comment]
Thanks for spotting this, it really should be documented somewhere, its due to the way the internals work.

**Comment by manoadamro** [comment]
for me,

This works:
`
    _dob = DateProperty(db_property='dob')

    @property
    def dob(self):

        return parse_date_to_iso8601(self._dob)

    @dob.setter
    def dob(self, value):

        self._dob = parse_iso8601_to_date(value)

`

But this does not:

`
    _lived_from = DateProperty(db_property='lived_from')

    @property
    def lived_from(self):

        return parse_date_to_iso8601(self._lived_from)

    @lived_from.setter
    def lived_from(self, value):

        self._lived_from = parse_iso8601_to_date(value)
`

Changing from _lived_from to lived_from_ didn't change anything for me :(

**Comment by aanastasiou** [comment]
@mjmare Thank you, this has now been addressed in the documentation.
