### ISSUE TITLE
Slow cypher query time

### ISSUE THREAD

**Issue by connorwake** [neo4j-contrib/neomodel#289]
We recently switched over to using neomodel in our project but we noticed that all of our query times nearly doubled. On further investigation we found that all of the cypher queries seem to have an overhead of 60ms.  So when we run multiple neomodel updates and connects we add 60ms each time.  As a test I ran the following (`tf` just returns the time taken in ms):
```
>>> tf(lambda: db.cypher_query("return 1+1"))
753.8211345672607
>>> tf(lambda: db.cypher_query("return 1+1"))
63.35592269897461
>>> tf(lambda: db.cypher_query("return 1+1"))
63.50302696228027
>>> tf(lambda: db.cypher_query("return 1+1"))
63.491106033325195
```
The first time takes a long time (as I'm assuming its setting up a new connection), then the rest will always take about 60ms.
I've tried both neo4j 3.1 and 3.3 and the same thing happens.  Using version 3.2.5 of neomodel.
Any ideas why these queries are taking so long?

**Comment by aanastasiou** [comment]
No...but it is interesting...Any updates on this?

**Comment by aanastasiou** [comment]
@connorwake any updates about this?

**Comment by AdrianPardo99** [comment]
Idk, if labels is the current problem, but I have check this:

https://stackoverflow.com/a/22548735/9179769

https://neomodel.readthedocs.io/en/latest/configuration.html#enable-automatic-index-and-constraint-creation
