### ISSUE TITLE
StringProperty unique_index has to be True for Nodes?

### ISSUE THREAD

**Issue by RSchlenker** [neo4j-contrib/neomodel#293]
Hey Guys,
I hope this is not too specific for an issue thread but I couldn't find any related information about my recent issue using StringProperties.

I would like to attach a String Property to a node but it shouldn't necessarily be unique to any other Property of similar nodes. The use case is: Provide a String field which can be used for additional informations.

Here is my code:

`class Person(StructuredNode):
    uid = UniqueIdProperty()
    name = StringProperty(unique_index=True)
    info = StringProperty()
    age = StringProperty()

class Event(StructuredNode):
    uid = UniqueIdProperty()
    name = StringProperty(required=True)
    info = StringProperty()
    started = DateTimeProperty()
    ended = DateTimeProperty()`

When I am trying to update the database models, I got error messages like this:

Finished 2 classes.
`
Exception AttributeError: "'NoneType' object has no attribute 'close'" in <bound method Connection.__del__ of <neo4j.bolt.connection.Connection object at 0x7f56b8380bd0>> ignored
Exception AttributeError: AttributeError("'NoneType' object has no attribute 'close'",) in <bound method DirectDriver.__del__ of <neo4j.v1.direct.DirectDriver object at 0x7f56b8373590>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'close'" in <bound method Connection.__del__ of <neo4j.bolt.connection.Connection object at 0x7f56b83809d0>> ignored
`
It is always only creating the properties which have the "unique_index=True" argument provided.
I also tried to set the unique_index to false but didn't got any further with it.
It is also not adding the subsequent Property types like DateTimeProperty started / ended.
Is this a bug or am I simply overseeing something obvious?

Btw, the reset data models script which is mentioned in the documentation is also not present on my installation from today.

Kind regards,
RSchlenker

**Comment by aanastasiou** [comment]
I don't think I understand what this question is about exactly and also, the traceback provided does not seem to point to a `neomodel` related problem.

Please provide a more detailed description or a more extensive code snippet and we can have another look at the problem.

All the best
