### ISSUE TITLE
Multi-Hop Traversal

### ISSUE THREAD

**Issue by cledoux** [neo4j-contrib/neomodel#297]
Is there a currently supported method for multi-hop traversals using the existing NodeSet?

Given the following model:

```
class First(StructuredNode):
    second = RelationshipTo('Second', 'SECOND')

class Second(StructuredNode):
    first = RelationshipFrom('First', 'SECOND')
    third = RelationshipTo('Third', 'THIRD')

class Third(StructuredNode):
    second = RelationshipFrom('Second', 'THIRD')
```

I want to be able to retrieve all `Third` reachable from `First` through `Second`.  The equivalent Cypher query is something like `MATCH (:First)-[:SECOND]->(:Second)-[:THIRD]->(matched :Third) RETURN matched`

At the moment, I'm just using a property that makes the Cypher query and calls `inflate()`:

```
class First(StructuredNode):

    @property
    def third(self):
        query = "MATCH (:First)-[:SECOND]->(:Second)-[:THIRD]->(matched :Third) RETURN matched"
        results, meta = self.cypher(query)
        return [Third.inflate(node[0]) for node in results]
```

It works, but it's a bit clunky and it breaks consistency with other relationship traversals. The output of my property is not the same as the output of a direct traversal via a relationship.

**Comment by aanastasiou** [comment]
@cledoux Can you please clarify this further? What exactly is the use case here? And what is it that is proposed?

Could this be addressed by [returning a path](https://github.com/neo4j-contrib/neomodel/issues/130#issuecomment-470167202) for example?

Otherwise, if you are simply interested in occasionally retrieving the *"...`Third` reachable from `First` through `Second`..."* given some `First` node, then the way you seem to be doing it is fine (?).

**Comment by cledoux** [comment]
I no longer work for the company where I hit this issue and I don't recall the details anymore.

IIRC, I think I was trying to use neomodel similar to the way I was used to using ORMs such as peewee: all queries go through the model and raw SQL is to be avoided if possible.  Similarly, I was trying to avoid raw Cypher queries with neomodel.  I believe I eventually gave up on this idea and just used neomodel as a light wrapper around the underlying py2neo with raw cypher used on every query.  This improved my consistency issue as well because I hardly ever retrieved nodes via the relationship properties.

I'm going to go ahead and close the issue since I don't have this issue anymore. :smiley:

**Comment by aanastasiou** [comment]
@cledoux No worries, thanks for letting us know and for the clarification.

**Comment by JiGGie145** [comment]
Hi all, I believe I am having the same issue.

How would u implement the equivalent of 
`MATCH (n:node_class)-[:relationship*0..]-(m:node_class) SET m.property=n.property`
but in Neomodel code, without using raw cypher?

I tried using the `neomodel.match.Traversal` class but it seems to only return the first level related nodes, could there be a parameter I am unaware of?
