### ISSUE TITLE
neomodel_remove_labels doesn't work

### ISSUE THREAD

**Issue by WaldenLian** [neo4j-contrib/neomodel#299]
I would like to report the potential problem of `neomodel_remove_labels`.

I installed `neomodel` on macOS 10.12, and it worked as expected. However, the terminal reported that `command not found: neomodel_remove_labels` when I wanted to remove the labels. But `neomodel_install_labels` worked as expected. 

Thus, I think there might be problems lying behind the functionality of `neomodel_remove_labels`.

**Comment by hannonq** [comment]
I can confirm that I have the same issue. 
Running on Ubuntu 17.10 and installed neomodel using conda.

**Comment by laky55555** [comment]
Hi,
Can you please try to install latest version via github 
`pip install git+git://github.com/robinedwards/neomodel.git@HEAD#egg=neomodel-dev`
[Documentation guide](http://neomodel.readthedocs.io/en/latest/#installation)
If error reoccurs can you please paste whole stack trace.
If I guess correctly, version on pypi (version that you install with pip) isn't the latest one, and in that one _remove_all_labels_ isn't there
Tnx

**Comment by WaldenLian** [comment]
@laky55555 Thanks for your reply. The problem is solved by installing the latest version.
