### ISSUE TITLE
Support generic (graph) usage

### ISSUE THREAD

**Issue by Pawamoy** [neo4j-contrib/neomodel#304]
I'm looking for a Python package that would allow me to manipulate neo4j data in a generic manner. I do not have a particular model like Friends or else, I just want to manipulate Nodes and Relationships.

Is there a way to use neomodel like that? Without having to define a `class Node(StructuredNode): pass`? I tried some time ago and I remember it didn't work for me.

**Comment by robinedwards** [comment]
There is nothing stopping you calling db.cypher_query().

But if I was you id just use neo4j-driver.

**Comment by Pawamoy** [comment]
Yes this is what I considered as well :) Directly using neo4j-driver. But I liked a lot the wrapping neomodel provides. I might end up writing a simpler neomodel hehe. Thanks :smile:

**Comment by Pawamoy** [comment]
Just for info, here is my attempt at doing so: https://github.com/Pawamoy/neopy. It's not even alpha, but contributions are still welcomed (ideas, docs, code, whatever)!
