### ISSUE TITLE
neomodel_remove_labels not found

### ISSUE THREAD

**Issue by craig1901** [neo4j-contrib/neomodel#314]
When running `neomodel_remove_labels`, response back is `command not found: neomodel_remove_labels`. There was a previous issue on this which seemed to be resolved by installing directly from git but neither approaches have worked for myself.

**Comment by mprahl** [comment]
@craig1901 this is because `neomodel_remove_labels` was introduced after the latest release of `neomodel` on PyPi. Although it'd be nice to have a new release... I've been able to use this script by installing directly from PyPi.
