### ISSUE TITLE
Creating StructuredNode models and relationships dynamically

### ISSUE THREAD

**Issue by millertime145** [neo4j-contrib/neomodel#318]
Thanks for the excellent work!

I'm trying to create StructuredNode models dynamically at run-time but I'm having some issues with creating relationships.

Basically I'm creating a web app (via Django) that allows users to upload a CSV file. I'm using the headers of the CSV file to create class names. A user can upload CSVs with anything as the headers: Book, Author, Publisher or Person, Car, Model  etc.

I'm going to use this example: A user uploads a CSV file with Person as the header of column 1 and Country as the header of column 2.

I'm using this to create the Person model: model1 = type(col1_header_name, (StructuredNode,), {'name' : StringProperty(unique_index=True, required=True), 'relatedto' = ''} # relatedto is a placeholder for the relationship to Country. More relationships will need to be added if there are more column headers (like a City column header in the CSV).

I'm using this to create the Country model: model2 = type(col2_header_name, (StructuredNode,), {'name' : StringProperty(unique_index=True, required=True), 'relatedto' = ''} # related is a placeholder for the relationship to Person.

I then try to add the relationship: model1.relatedto = Relationship(col2_header_name, 'RELATED_TO') and model2.relatedto = Relationship(col1_header_name, 'RELATED_TO')

Creating the nodes works fine: p = model1.get_or_create({'name' : 'Jim'})[0] and c = model2.get_or_create({'name' : 'Germany')[0]

But when I try p.relatedto.connect(c) I get an error: RelationshipDefinition does not have a connect method.

Question: Is there something I'm doing wrong or a better method for dynamically creating StructuredNode models and adding relationships to those models so I can adjust to dynamic CSV datasets? I've tried creating a generic Node class in my models.py and but that limits the Label for the node to 'Node' and I can't dynamically add relationships to the Node class.

I appreciate any help!

**Comment by mmatchyn** [comment]
This might help:
https://stackoverflow.com/questions/43229844/neo4j-create-a-node-type-dynamically

**Comment by nilanjan-samajdar** [comment]
This problem happens because the RelationshipDefinition is not getting updated to a RelationshipManager.

I used this workaround which worked for me :
I explicitly called the `RelationshipDefinition .build_manager()` when creating a relationship
```

        for name in neoObject.__class__.__dict__.keys():
            obj = neoObject.__class__.__dict__[name]
            if isinstance(obj, RelationshipDefinition):
                setattr(neoObject.__class__, name, obj.build_manager(neoObject, name))

```

**Comment by akapula1** [comment]
@nilanjan-samajdar 
I followed all the steps mentioned above. At line 'setattr(neoObject.__class__, name, obj.build_manager(neoObject, name))' I get an error "module 'IPython.core.interactiveshell' has no attribute 'Country' ". I am not able to figure out what is wrong. Can you please help?

**Comment by aanastasiou** [comment]
@millertime145, @nilanjan-samajdar , @akapula1 

1. I do not see how `neomodel` can help you with the dynamic definition of a schema in this way. To me it looks like making things more difficult than they are. This is because, you still need to capture that schema, the entities and their relationships in some way and at the moment it seems that this way of "capturing" the schema is only through the columns of the CSV. If those were to change, then the whole schema becomes invalid. But anyway, that's just a note, without knowing more details about your use case.

2. You have to realise that what you create through `some_model = type(...)` is exactly that. **a type**. So, the full cycle of *appropriately* instantiating an object would be something like:

```
import neomodel

# some_model here is equivalent to a !!!CLASS DECLARATION!!!
some_model = type("Person", (neomodel.StructuredNode,), {"name":neomodel.StringProperty(), "uid":neomodel.UniqueProperty()})

# Now we need to create an object of that class

some_object = some_model(name="Nikola Tesla").save() # Or any other valid neomodel form
```

This works **in exactly the same way** for relationships too:

```
import neomodel

class Country(neomodel.StructuredNode):
    pass

some_model = type("Person", (neomodel.StructuredNode,), {"name":neomodel.StringProperty(), "rel":neomodel.RelationshipTo(Country,"FROM_COUNTRY")}) 

some_object = some_model(name="Nikola Tesla").save()

# At this point, some_object has been instantiated appropriately and has all the methods that are expected of the attribute "rel" (such as connect, etc).
```

3. The reason why the above code raises an iPython related exception (@akapula1 ), is because it is trying to import "Country". To avoid that error, put the **class name** (Country), instead of the string definition and `neomodel` will reference the class properly.

Hope this helps.

**Comment by akapula1** [comment]
@aanastasiou Thanks for the answer. But the way I am creating a dynamic neomodel is from a JSON schema. 

{
  "Type":"Person",
  "Properties":{"FirstName":"John", "MiddleName":"", "LastName":"Newquist", "Age":3},
  "RelatedObjects":
  [
      {"type":"Country","desc":"lives_in", "Properties":{"Country":"USA"}},
      {"type":"Phone", "desc":"has_phone", "Properties":{"phone":"12321442"}}
  ],
}

Here is my sample code:

model1 = type(gen_dict['Template Type'], (StructuredNode,), {'name' : StringProperty(unique_index=True, required=True), 'relatedto':''})
model2 = type(gen_dict['RelatedObjects'][0]['type'], (StructuredNode,), {'name' : StringProperty(unique_index=True, required=True), 'relatedto' : ''})

model1.relatedto = RelationshipTo(gen_dict['RelatedObjects'][0]['type'], 'RELATED_TO')
model2.relatedto = RelationshipFrom(gen_dict['Template Type'], 'RELATED_TO')

p = model1.create_or_update({'name' : 'Jim'})[0]
c = model2.create_or_update({'name' : 'USA'})[0]

for name in p.__class__.__dict__.keys():
    obj = p.__class__.__dict__[name]
    print(obj)
    if isinstance(obj, RelationshipDefinition):
        setattr(p.__class__, name, obj.build_manager(p, name))

As you said, my both by class name and StringDefinition names are 'Country'.

**Comment by akapula1** [comment]
@aanastasiou 
Thanks for the answer!
How to pass a dictionary of properties to some_model instead of single property (name = "Nikola Tesla") 
`some_object = some_model(name="Nikola Tesla").save()`

**Comment by MiroslavHoudek** [comment]
@aanastasiou Hi, this has been amazingly helpful, thanks ... but I got stuck fast anyway :-) You wouldn't happen to have a pointer how to leverage this into building dynamic objects, and refer to those (and also do self-reference) ?

some_model = type("Person", (neomodel.StructuredNode,), {"name":neomodel.StringProperty(), "rel":neomodel.RelationshipTo( **"?Person (i.e. some_model)?"** ,"FRIENDS_WITH")})

to establish a type/StructuredNode "Person", but also with a relationship to some other node of type "Person"? 

It's seems that neomodel is not exactly built for this.
