### ISSUE TITLE
exception.py renamed to exceptions.py

### ISSUE THREAD

**Issue by robertlagrant** [neo4j-contrib/neomodel#323]
[This commit](https://github.com/neo4j-contrib/neomodel/commit/115414884ff6261124c110cacbfd0dd87a514380#diff-673f598273e3dfcbe8daca6f8ce84605) caused me some head-scratching late last night, because I'd got 3.2.5 installed in some places and yet tox was getting the latest neomodel, so one or the other was always saying exception[s].py not found!

Is it worth documenting this loudly, or even adding back in exception.py that just imports from exceptions.py with a warning that support will drop? I may be biased from my recent experience but it was pretty confusing!

**Comment by The-E** [comment]
IMHO, changes like these are breaking changes that should be discussed more or better documented with clear error messages or warnings. A version bump from one minor revision to the next should (ideally, anyway) not make it necessary for developers to go through their code to figure out why all their tests are suddenly failing.

**Comment by robinedwards** [comment]
My apologies, it was a PR I merged with out thinking of the consequences and in retrospect it should have gone into a major version release
