### ISSUE TITLE
using params in db.query breaks query

### ISSUE THREAD

**Issue by manoadamro** [neo4j-contrib/neomodel#330]
Using 'params' in db.cypher_query seems to break some queries.

```python
    query = """
        match (p:P)-[r:ASSIGNED_TO]-(l:L)
        where p.uuid="{p_uuid}" and l.uuid="{l_uuid}"
        set r.bookmarked={value}
        return p
    """.format(l_uuid=l_id, p_uuid=p_id, value=value)

    results, meta = db.cypher_query(query)
```
works absolutely fine. 1 result, all good.

```python
    query = """
        match (p:P)-[r:ASSIGNED_TO]-(l:L)
        where p.uuid="{p_uuid}" and l.uuid="{l_uuid}"
        set r.bookmarked={value}
        return p
    """
    results, meta = db.cypher_query(query, {'l_uuid': l_id, 'p_uuid': p_id, 'value': value})
```
throws an ```IndexError``` because there are no results

```l_uuid``` and ```p_uuid``` are uuid4s
```value``` is a string (either ```'true'``` or ```'false'```, i have tried using python ```True```/```False``` thinking that perhaps they would be converted, but it didn't make a difference)

I can go immediately to the browser and manually select it using the exact same query and both nodes are returned.
Because i can't log the query after calling ```db.cypher_query()```, i can't see what it is doing to the parameters.

(this should probably be a separate issue)
I noticed that bolt was logging loads of stuff, so i had set an environment variable to 0 (which seemed to stop this happening)
I wanted to allow bolt to log again so i could debug the above issue but setting it to ```1``` or true has not re enabled logging, i can print ```os.environ['NEOMODEL_CYPHER_DEBUG']``` and it is indeed ```1```, however no logs to be seen.

**Comment by manoadamro** [comment]
Ok so after a very, very long time searching, it turns out that using 'params' will automatically wrap the strings with quotes, using .format() you have to add your own quotes

The lack of logging really made debugging this difficult though

**Comment by bjm88** [comment]
neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead

need to use $param in cipher, not older {}

**Comment by anentropic** [comment]
the docs here (3.3.2) still appear to show `{param}` syntax:
https://neomodel.readthedocs.io/en/latest/cypher.html

**Comment by Amohammadi2** [comment]
Please add more examples of raw cypher queries that address more complex use-cases. Also please add examples of providing extra parameters (other than self) to the query
