### ISSUE TITLE
Filter with OR

### ISSUE THREAD

**Issue by sbabashahi** [neo4j-contrib/neomodel#332]
Recently I start to useing neo4j and neomodel and now I need to filter 2 parameters with OR in neomodel. I searched in document and codes but couldn't find anything about it. In django model there is a Q object to handle OR in queries. How can handle OR query in neomodel?

**Comment by cr17ms** [comment]
I made some changes to solve this issue in #336.

**Comment by MardanovTimur** [comment]
close this issue
