### ISSUE TITLE
There is no way to connect to multiple databases from a single process.

### ISSUE THREAD

**Issue by vaibhavmoengage** [neo4j-contrib/neomodel#340]
USE CASE: We have two neo4j clusters. We want to redirect data to different cluster on the basis of certain keys. The decision to redirect data is to be taken from within the process. So i need a way to create a database connection which takes a input parameter as url.

**Comment by reorx** [comment]
may I ask why this issue was closed? I still can't find any way to connect to multiple databases in a single process
