### ISSUE TITLE
Maximum Number of Relationships

### ISSUE THREAD

**Issue by HashRocketSyntax** [neo4j-contrib/neomodel#352]
It would be nice to define the number of relationships that can exist between two types of nodes. Not only for uniqueness, but also for logic.

```
class Sedan(StructuredNode):
    seat = RelationshipFrom('SEAT', 'INCLUDED_IN', max_rels=4)
    # this sedan can have up to 4 seats
```

```
class Person(StructuredNode):
    car = RelationshipFrom('CAR', 'OWNED_BY', max_rels=1)
    # this car can only have up to 1 owner
```

```
class Router(StructuredNode):
    devices = RelationshipFrom('ROUTER', 'CONNECTED_TO', max_rels=30)
```
I am aware that I could do this easily enough in application logic with simple if statements, but it would be nice not to have to write them. I keep winding up with these duplicate relationships when things slip through in testing.

I suppose I'm just scared to dive into the world of open source contribs =\

**Comment by aanastasiou** [comment]
Not exactly helping but this is a [Multiplicity](https://en.wikipedia.org/wiki/Class_diagram#Multiplicity) constraint and the foundation for doing this is already there in [StructuredRel](http://neomodel.readthedocs.io/en/latest/relationships.html) via Cardinality. It is a matter of adding the constrain checks.
