### ISSUE TITLE
StructuredRel.start_node() throws an AttributeError

### ISSUE THREAD

**Issue by henryfjordan** [neo4j-contrib/neomodel#357]
I ran some code like the following to get and inflate a relationship, then get the start_node for that relationship:

```python
results, meta = db.cypher_query("MATCH ()-[r]->() WHERE r.some_id = 3 RETURN r")
r = [StructuredRel.inflate(rel) for row in results for rel in row]
r.start_node()
```

I get an exception:
```
AttributeError: \\'StructuredRel\\' object has no attribute \\'_start_node_class\\''"
```

The way some of this code is constructed is a little convoluted for me to fix. `RelationshipManager` seems to have the internal methods that `StructuredRel.start_node()` seems to reference but trying to import it to base `StructuredRel` off of results in circular import issues. Any fix is going to require some serious structural changes to this library it seems.

I'm happy to contribute a fix but I'll need some guidance.

**Comment by aanastasiou** [comment]
@henryfjordan In an ideal scenario, `.inflate()` would only have to be called in very special cases.

[This](https://github.com/neo4j-contrib/neomodel/pull/421) will ensure that you receive properly instantiated `StructuredRel`s from the database and then you would indeed be able to ask for their end point nodes.

**Comment by henryfjordan** [comment]
yeah, this one is pretty old, I think it's fair to close
