### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SyntaxError'

### ISSUE THREAD

**Issue by shalaka92** [neo4j-contrib/neomodel#359]
neo4j - 3.4.1 version
py2neo - 2.0.8
anaconda - version 1.6.14

I was trying this code in jupyter notebook with python2- 
graph = Graph()
graph.cypher.execute("MATCH A DETACH DELETE A;")
load_graph("4642026")
summarize_opinions()

Got this as error - ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-8aaee30e81fb> in <module>()
      2 #graph = Graph('http://localhost:7474/db/data')
      3 
----> 4 graph.cypher.execute("MATCH A DETACH DELETE A;")
      5 load_graph("4642026")
      6 summarize_opinions()

/home/shalaka/anaconda2/lib/python2.7/site-packages/py2neo/cypher/core.pyc in execute(self, statement, parameters, **kwparameters)
    134             tx = CypherTransaction(self.transaction_uri)
    135             tx.append(statement, parameters, **kwparameters)
--> 136             results = tx.commit()
    137             return results[0]
    138         else:

/home/shalaka/anaconda2/lib/python2.7/site-packages/py2neo/cypher/core.pyc in commit(self)
    331         log.info("commit")
    332         try:
--> 333             return self.post(self.__commit or self.__begin_commit)
    334         finally:
    335             self.__finished = True

/home/shalaka/anaconda2/lib/python2.7/site-packages/py2neo/cypher/core.pyc in post(self, resource)
    286             if len(errors) >= 1:
    287                 error = errors[0]
--> 288                 raise self.error_class.hydrate(error)
    289         out = RecordListList()
    290         for result in j["results"]:

/home/shalaka/anaconda2/lib/python2.7/site-packages/py2neo/cypher/error/core.pyc in hydrate(cls, data)
     52         _, classification, category, title = code.split(".")
     53         error_module = import_module("py2neo.cypher.error." + category.lower())
---> 54         error_cls = getattr(error_module, title)
     55         inst = error_cls(message)
     56         inst.code = code

AttributeError: 'module' object has no attribute 'SyntaxError'

**Comment by aanastasiou** [comment]
This is a [py2neo](https://github.com/nigelsmall/py2neo) issue, not a [neomodel](https://github.com/neo4j-contrib/neomodel) issue.
