### ISSUE TITLE
EmailProperty seems to be required

### ISSUE THREAD

**Issue by HashRocketSyntax** [neo4j-contrib/neomodel#369]
Despite `email_distribution = EmailProperty(required=False,...` the validation for Email Property seems to be required. 

For example, when I try to submit a blank email field I get this back:
`'' does not matches '[^@]+@[^@]+\\.[^@]+'`

**Comment by HashRocketSyntax** [comment]
Is the problem that `RegexProperty` must always pass?

https://github.com/neo4j-contrib/neomodel/blob/99123aeb363f245aadbbced831b6dac03dba4521/neomodel/properties.py

**Comment by HashRocketSyntax** [comment]
Also, this regex looks more complete:
https://stackoverflow.com/a/201378/5739514

**Comment by HashRocketSyntax** [comment]
More thorough email regex 
https://stackoverflow.com/a/201378/5739514

**Comment by StevenMapes** [comment]
This is not a bug but is a you misunderstanding what the ```required=False``` attribute means.

By setting the property as optional i.e. ```required=False``` you are saying that you do not need to set the property at all or you can set it to ```None```. Setting it to an empty string is not the same as ```None``` as it has a value (an empy string) and thus it does not match the regex.

Here is an example of a simple class which I will try to save two instances of, one that will fail as it has an invalid email of an empty string and then the 2nd which will show the correct way of using the object

```
from neomodel import StructuredNode, StringProperty, EmailProperty

class SteveTest(StructuredNode):
    email=EmailProperty(required=False)
    name=StringProperty(required=True)

s = SteveTest(name="Should Fail", email="")
s.save()
# ValueError: '' does not matches '[^@]+@[^@]+\\.[^@]+'

# Don't set the property
s = SteveTest(name="Will work")
s.save()
# <SteveTest: {'email': None, 'name': 'Should Fail', 'id': 1}>

# Set the property to None
s1 = SteveTest(name="Or you can do this", email=None)
s1.save()
# <SteveTest: {'email': None, 'name': 'Should Fail', 'id': 2}>
```

**Comment by leonaidus** [comment]
@StevenMapes can we change the error message to more readable form.
"Invalid Email" or something

**Comment by HashRocketSyntax** [comment]
I remember explicitly handling "" empty strings and setting them to None. As well as setting required to False.

I think this was more about the required = True tripping some flag that could not be flipped back properly. Sorry for being vague - forked a while back.

**Comment by aanastasiou** [comment]
@HashRocketSyntax  Thank you, this has now been highlighted in the documentation and will be rolled out in an upcoming release.
