### ISSUE TITLE
Using neomodel with Django user authentication and AbstactBaseUser

### ISSUE THREAD

**Issue by jxwolstenholme** [neo4j-contrib/neomodel#375]
Hi there,

I'm wondering if anybody has had any success with using neomodel to store and retrieve users for authentication with Django's inbuilt auth system? 

If so, I'm wondering if there is some way to subclass the AbstractBaseUser class and the BaseUserManager to be able to achieve this?

Would really appreciate any guidance on best practice or if it is even possible!!

Many Thanks

**Comment by robinedwards** [comment]
Hi, I don't have this code available to me but yes I did that on a project 6 years ago using neomodel. It would be great to have this as a contrib to the neomodel django module

**Comment by jxwolstenholme** [comment]
Thanks for getting back to me @robinedwards 

Desperately trying to get my head around this - nowhere near being able to contribute unfortunately.

Is there a way that a new User class could inherit from both StructuredNode and AbstractBaseUser?
All I'm getting is metaclass conflicts so I imagine that the bodge that I'm trying to achieve is incredibly far off the mark.

`class UserProfile(DjangoNode, AbstractBaseUser):
    first_name = StringProperty(required=True)
    last_name = StringProperty(required=True)
    date_of_birth = DateProperty(required=True)
    SEXES = {'F': 'Female', 'M': 'Male', 'O': 'Other'}
    sex = StringProperty(required=True, choices=SEXES)
    email = EmailProperty(unique_index=True, required=True)
    password = StringProperty(required=True)
    phone = StringProperty(required=True)
    country = StringProperty()
    date_joined = DateTimeProperty(required=True)
    uid = UniqueIdProperty()
    last_login = DateTimeProperty()
    is_active = BooleanProperty(default=True)
    is_authenticated = BooleanProperty(default=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'date_of_birth', 'sex', 'phone', 'country']
    objects = CustomUserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        abstract = False

    def get_absolute_url(self):
        return "users/%s/" % urlquote(self.email)

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name
    def email_user(self, subject, message, from_email=None):
        send_mail(subject, message, from_email, [self.email])`

Any chance that you might have some pointers for what to look in to?

**Comment by robinedwards** [comment]
If AbstractBaseUser is an actual Django model then it probably wont work that way. You may just need to implement the same functionality as BaseUser.

Personally having been down this route, I wouldn't do it again. You loose the integration with all the Django plugins / extensions by not using the Django ORM.
