### ISSUE TITLE
Enhancement: Change in filter functionality

### ISSUE THREAD

**Issue by leonaidus** [neo4j-contrib/neomodel#383]
I would suggest to pass object or dict to nickname or any property giving filter as key and value as search value.
Like  `Person.nodes.filter(nicknames={ 'has': 'Tom' }).all()`

If think so i am ready to start with this.

**Comment by aanastasiou** [comment]
Can I please ask if this was meant to be a comment to [this](https://github.com/neo4j-contrib/neomodel/issues/379) issue?

**Comment by leonaidus** [comment]
@aanastasiou mentioned issue is similar in the request to change filter functionality. But @mprahl wants the result to be changed into an iterable. On the other hand i am proposing a complete functionality change for "filter".

**Comment by aanastasiou** [comment]
@leonaidus Alright, can we please:

1. Keep one discussion for things that are very much related.
    * Can you please write about your idea / issue in the ticket that is already open?

2. Both you and @mprahl, can you please create a brief test case on how the current functionality does not fit your use case and how you propose to change it? ([Here](https://github.com/aanastasiou/neomodelInheritanceTest) is an example. You can always fork neomodel, work on it and suggest the solution in a separate PR.

All the best
