### ISSUE TITLE
ModelDefinitionMismatch exceptions in Flask after 3.3.0

### ISSUE THREAD

**Issue by mzgajner** [neo4j-contrib/neomodel#388]
I'm working on an app that uses Flask and neomodel 3.3.0. I had issues with `ModelDefinitionMismatch` exceptions being raised when there was no good reason for them. Googled for a bit and found this [StackOverflow issue](https://stackoverflow.com/questions/52877575/flask-and-neomodel-modeldefinitionmismatch) where someone has the same problem.

The answer was to downgrade to 3.2.9 because, quote:

> Looks like they introduced _NODE_CLASS_REGISTRY under neomodel.Database, object which is meant to be a singleton. But with Flask it's not necessarily a singleton because it keeps instantiating new instances of Database with empty _NODE_CLASS_REGISTRY.

It helped my case too and I was just wondering whether this is a known thing. Is there a way to explicitly keep my Database instance on Flask's `g` object or something along those terms?

**Comment by aanastasiou** [comment]
Hello, thank you very much for bringing this to our attention, it is very useful. Can you please post this under https://github.com/neo4j-contrib/neomodel/issues/378 which is where we are dealing with this issue.

All the best

**Comment by mzgajner** [comment]
Sorry, should have read through that issue more carefully, tnx!

**Comment by aanastasiou** [comment]
No worries, this was really helpful.
