### ISSUE TITLE
Is it possible to return a Queryset from neomodel?

### ISSUE THREAD

**Issue by jxwolstenholme** [neo4j-contrib/neomodel#394]
Wondering if Neomodel has support for returning objects as querysets?

When I request Model.objects.all() from the standard Django ORM it returns a response in the format:

<QuerySet [<Model: field>, <Model: field>,....]>

But using Neomodel's Model.nodes.all() it returns:

[<Model: {'field_name_1': 'field', 'field_name_2': 'field_2}>, <Model: {'field_name_1': 'field', 'field_name_2': 'field_2}>]

Is it possible to get the output in the standard queryset format?

Thanks

**Comment by aanastasiou** [comment]
@jxwolstenholme Will have a look and get back to you about this but in the meantime, just a naive question: If the `QuerySet` returns something of the form `[ <Model:...>, <Model:...>, ...]` doesn't that mean that it has already been evaluated? In this case, perhaps you could "transform" the list of results to a `QuerySet` (?).

**Comment by oikonomou** [comment]
@jxwolstenholme You are right, there is a difference between Django and Neomodel but in terms of returned types.
Django queryset method "all" returns a new Queryset instance whereas Neomodel queryset method 'all" returns a List of <Model> objects.

@aanastasiou  To answer you question, Django Queryset does not evaluate the results. This format of the printed Queryset is because of the way Queryset is represented (Queryset.__repr__ builtin method). So when executing the Queryset in the shell, the representation is called and executes the queryset but only in this case.

**Comment by aanastasiou** [comment]
@jxwolstenholme @oikonomou I believe that this issue is related to [this one](https://github.com/neo4j-contrib/neomodel/issues/232), please let me know if you agree and then I will mark just one as a possible enhancement.

**Comment by Ramel** [comment]
I've seen in *neo4django* a [NodeQuerySet](https://github.com/scholrly/neo4django/search?utf8=%E2%9C%93&q=NodeQuerySet&type=) that seems returns a queryset.
A queryset for Django will be added to django_neomodel? Or it will be added to neomodel in the future?
As read in the wiki page: [TODOs-&-Enhancements](https://github.com/neo4j-contrib/neomodel/wiki/TODOs-&-Enhancements).

**Comment by aanastasiou** [comment]
@Ramel I am sorry I picked this up so late. Modifications to the `neomodel` NodeSet are possible. However, the project you are linking is unrelated to `neomodel`. Maybe something to raise with that project separately (?)

**Comment by aanastasiou** [comment]
@Ramel Sorry for the delay in picking this up, there is always [this](https://github.com/neo4j-contrib/django-neomodel) project to try when integrating with django.

**Comment by vbo75** [comment]
@jxwolstenholme I face the same problem. In order to bypass this issue, I overload filter() and get() functions in a specific QuerySet class and create a dedicated Manager who call this QuerySet.
In filter() and get(), I use Neomodel API to retrive nodes and build a QuerySet object as expected by Django. Here an exemple that works.

In models.py
```python
from django.db import models
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from neomodel import StructuredNode, StringProperty, RelationshipTo, StructuredRel, \
    DoesNotExist, MultipleNodesReturned

class Movie(StructuredNode):
    uid = StringProperty(primary_key=True)
    title = StringProperty()
    tagline = StringProperty()
    released = StringProperty()
    _default_manager = MovieManager()

class MovieManager(models.Manager):
    def get_queryset(self):
        return MovieQuerySet(self.model, using=self._db)

class MovieQuerySet(models.QuerySet):
    def filter(self, *args, **kwargs):
        nodeSet = Movie.nodes.filter(**kwargs)
        i = 0
        for value in nodeSet:
            self._known_related_objects[i] = value
            i += 1
        return self

    def get(self, *args, **kwargs):
        if not kwargs:
            if len(self._known_related_objects) == 1:
                print('One node find in _known_related_objects')
                node = self._known_related_objects[0]
            else:
                if len(self._known_related_objects) == 0:
                    print('No node find in _known_related_objects')
                    raise ObjectDoesNotExist
                else:
                    print('Multiple nodes find in _known_related_objects')
                    raise MultipleObjectsReturned
        else:
            try:
                print('Try to get a node with kwargs param')
                node = Movie.nodes.get(**kwargs)
            except MultipleNodesReturned:
                print('Multiple nodes returned')
                raise MultipleObjectsReturned
            except DoesNotExist:
                print('No node find')
                raise ObjectDoesNotExist
        return node
````
In views.py
```python
class DetailView(generic.DetailView):
    model = Movie
    template_name = 'MovieWeb/detail.html'
    context_object_name = 'movie'

    slug_field = 'uid'
    slug_url_kwarg = 'uid'
```
