### ISSUE TITLE
deflate error on nullable field

### ISSUE THREAD

**Issue by manoadamro** [neo4j-contrib/neomodel#397]
I have added a property to a model.
```
dod_ = DateProperty(db_property="dod", required=False, default=None)
```

however, when I try to get a node using `model.nodes.get_or_none(**filter_by)`
where `filter_by` contains `"dod_": None`

I get the following error,
```
neomodel.exceptions.DeflateError: Attempting to deflate property 'dod_' on None of class 'Patient': datetime.date object expected, got None
```

weirdly, I have another field:
```
dob_ = DateProperty(db_property="dob", required=False, default=None)
```
which works fine because it's never actually null.

Is it even possible to have a nullable date field?

**Comment by anindyamanna** [comment]
Just stumbled upon this as well. @manoadamro Is this solved?
