### ISSUE TITLE
Fetching nodes by neo id

### ISSUE THREAD

**Issue by mjamei** [neo4j-contrib/neomodel#400]
I know there have been multiple questions on this topic, but I am not sure if they answer my specific question/issue.

I am trying to do the following:

At first, I was using `UniqueIdProperty()` for my `uid`. I don't want to allow the user to add a new node that already exists (all properties are similar to the existing node except the `uid` of course). However, because the `uid` is different, it creates a new node in the graph.

If I remove the `UniqueIdProperty()`, I have no way of accessing my nodes with their id, since neomodel does not give access to neo4j native ids.

**Comment by oikonomou** [comment]
@mjamei If I understand your question correctly, the uniqueness of a node in your world is a tuple of values, meaning that a combination of properties forms the uniqueness of the node.  
Therefore, when user wants to create a node, the mentioned tuple has to be checked so that a new node to (not) be created, nothing related to uid.

**Comment by mjamei** [comment]
Yes that's exactly right. And the uid property is a nuisance in this case.

**Comment by oikonomou** [comment]
Then it's not that you need a separate property keeping uid but a constraint checking the uniqueness of your tuples.
You can do this a) through implementation on your create_node method or [having a db constraint](https://neo4j.com/docs/cypher-manual/current/schema/constraints/#constraints-create-a-node-key).

**Comment by mjamei** [comment]
Sure, I can do that. But then how do I get a node using its id?

**Comment by aanastasiou** [comment]
What you are looking for is ["Composite Keys"](https://github.com/neo4j-contrib/neomodel/issues/286), this is not yet possible from within `neomodel` but the constraint can still be setup as indicated in #286 or as has been suggested in an earlier comment.

> Sure, I can do that. But then how do I get a node using its id?

There is nothing stopping you from retrieving a node by a field such as `uid`. The `UniqueIdProperty` property generates a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier). (?)
