### ISSUE TITLE
How to define validator function in model like we do in django model and how to define in create_at and update_at?

### ISSUE THREAD

**Issue by varunajmera0** [neo4j-contrib/neomodel#401]
I want created_at and updated_at fields and validators function like django model

class User(DjangoNode):
   
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)
    uid = UniqueIdProperty()
    first_name = StringProperty(required=True, inflate=[validate_even])
    middle_name = StringProperty()
    last_name = StringProperty()
    email = EmailProperty(required=True)
    mobile = IntegerProperty(required=True)
    created = DateTimeProperty(default=datetime.utcnow)

    class Meta:
        db_table = 'users'

**Comment by aanastasiou** [comment]
Covered [here](https://neomodel.readthedocs.io/en/latest/module_documentation.html#neomodel.properties.DateTimeProperty)
