### ISSUE TITLE
Feature request: add lazy option to QueryBuilder

### ISSUE THREAD

**Issue by machosec** [neo4j-contrib/neomodel#404]
Hi, 
The `StructuredNode` class create/merge (`create_or_update`) functions has the `lazy` argument to only retrieve the id of the node tied to neo4j instead of all of its properties. This feature is great for many use cases.
I didn't find such option within the `QueryBuilder` that is used by the `NodeSet` and `Traversal` classes which seemed trivial to implement. Is there any reason why this feature does not exist? I guess this could be implemented in the `build_node` function. I can make a PR with this feature if you like.

Keep up the good work!

**Comment by machosec** [comment]
Hi @MardanovTimur 
The reason to make it `lazy` is to avoid returning the entire neo4j node from the beginning. Retrieving lots of nodes with non-indexed properties is expensive. a pythonic solution like `partial` does not solve this issue unless I don't understand the usage

**Comment by aanastasiou** [comment]
@machosec If I understand this correctly, you want the **last** call to only return IDs, rather than any intermediate ones because these intermediate might need the attributes for filtering (?), is that right?
