### ISSUE TITLE
DeflateError when dealing with Hebrew chars

### ISSUE THREAD

**Issue by machosec** [neo4j-contrib/neomodel#405]
Hi,
I get a `DeflateError` with the error message `'ascii' codec can't decode byte <byte> in position <num>: ordinal not in range(128)` when trying to deflate a `StringProperty` that contains Hebrew characters.

You can try to test it with a `StringProperty` with the value: `"בדיקה"` (\xd7\x91\xd7\x93\xd7\x99\xd7\xa7\xd7\x94)

**Comment by aanastasiou** [comment]
Are you [using Python 2.x](https://docs.python.org/2/howto/unicode.html) by any chance?

**Comment by aanastasiou** [comment]
Prior to Python 3.0 there is [explicit provision for unicode strings](https://github.com/neo4j-contrib/neomodel/blob/master/neomodel/properties.py#L16) in `neomodel`. However, the conversion (the translation of special characters to multi-byte sequences), is not automatic and depends on the encoding. The previous link I posted goes into much more detail about this and contains examples of this conversion process.

**Comment by machosec** [comment]
Got it. I guess it's time to upgrade to Python 3 :) 
Closing.
