### ISSUE TITLE
nodes.get(location=NeomodelPoint((0, 0), crs='cartesian') does not work

### ISSUE THREAD

**Issue by DmitriyG228** [neo4j-contrib/neomodel#417]
Hi, getting nodes with location, specified with NeomodelPoint give an error "Invalid instantiation via no arguments", while setting  node in the same way works well (below it gives ConstraintError). What is the right way of getting nodes with specific location?

```
location=(51.3454, -6.2434)
try:
    property = Property.nodes.get(location=NeomodelPoint(location,crs='cartesian'))
except:
    property = neo4j.Property(location=NeomodelPoint(location,crs='cartesian')).save()
```

ValueError: Invalid instantiation via no arguments. A Point needs default values either in x,y,z or longitude, latitude, height coordinates

ValueError: Invalid instantiation via no arguments. A Point needs default values either in x,y,z or longitude, latitude, height coordinates

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dmitriy/anaconda3/lib/python3.7/site-packages/neomodel/util.py", line 211, in cypher_query
    response = session.run(query, params)
  File "/Users/dmitriy/anaconda3/lib/python3.7/site-packages/neo4j/v1/api.py", line 331, in run
    self._connection.fetch()
  File "/Users/dmitriy/anaconda3/lib/python3.7/site-packages/neo4j/bolt/connection.py", line 287, in fetch
    return self._fetch()
  File "/Users/dmitriy/anaconda3/lib/python3.7/site-packages/neo4j/bolt/connection.py", line 327, in _fetch
    response.on_failure(summary_metadata or {})
  File "/Users/dmitriy/anaconda3/lib/python3.7/site-packages/neo4j/v1/result.py", line 70, in on_failure
    raise CypherError.hydrate(**metadata)
neo4j.exceptions.ConstraintError: Node(2484) already exists with label `Property` and property `location` = {geometry: {type: "Point", coordinates: [51.3454, -6.2434], crs: {type: link, properties: {href: "http://spatialreference.org/ref/sr-org/7203/", code: 7203}}}}

**Comment by aanastasiou** [comment]
@DmitriyG228 Can you please try `.get`ting with `NeomodelPoint(x=location[0], y=location[1], crs='cartesian')`?

**Comment by DmitriyG228** [comment]
aanastasiou, `Property.nodes.get(location=NeomodelPoint(x=location[0],y=location[1],crs='cartesian'))` gives the same error (ValueError: Invalid instantiation via no arguments. A Point needs default values either in x,y,z or longitude, latitude, height coordinates)

**Comment by DmitriyG228** [comment]
@aanastasiou, do you maybe have other ideas on this issue, or it is a real bug to fix?

**Comment by aanastasiou** [comment]
@DmitriyG228 let me have a look at it please. This exception is raised by `NeomodelPoint` itself.

Were the data stored in the dB via `neomodel`?

**Comment by DmitriyG228** [comment]
@aanastasiou, data is stored locally in neo4j, if I have got your question right

**Comment by aanastasiou** [comment]
@DmitriyG228 Yes, but was it stored via a neomodel model in the first place? Was it stored via the `Property` entity?

**Comment by aanastasiou** [comment]
The problem here stems from the way the Q expressions get combined. 

The exact point of failure is in the constructor of `NeomodelPoint` and can be triggered via the following:

```
import copy
import neomodel.contrib.spatial_properties

a_point = neomodel.contrib.spatial_properties.NeomodelPoint((0,0),crs="cartesian")
b_point = copy.deepcopy(a_point)
```

An update will follow shortly, tahnk you for flagging this.

**Comment by aanastasiou** [comment]
@DmitriyG228 Please see [here](https://github.com/neo4j-contrib/neomodel/pull/418).

I have tested this with a few alternative test cases myself and it seems to be working but please, have a go at it through your use case and let us know for any odd behaviours.

All the best

**Comment by DmitriyG228** [comment]
@aanastasiou, soory for noob question, how can I get the updated module to my machine?

**Comment by DmitriyG228** [comment]
@aanastasiou, I have just made the same changes in the module file and now my code seems to be working as expected. Thank you!

**Comment by aanastasiou** [comment]
@DmitriyG228 No worries. The most straightforward way would be to clone [this repo](https://github.com/aanastasiou/neomodel/tree/fix_NeomodelPoint_copy_operations) and then from within your virtual environment run something like `pip install -e ./` in the directory that contains the `setup.py` file. But in time, these changes will be merged with the master branch of `neomodel` and eventually make it to a release.

All the best
