### ISSUE TITLE
ClassAlreadyDefined

### ISSUE THREAD

**Issue by mdelmans** [neo4j-contrib/neomodel#424]
I'm playing with a package with multiple modules. What is the best way to avoid ClassAlreadyDefined error. I have a neodefs.py file with Node definitions and want to use in several dependent modules. How do I import without causing ClassAlreadyDefined ?

**Comment by aanastasiou** [comment]
@mdelmans Can you make that a bit more specific please?

Once a module is imported, Python will not attempt to import it again. `ClassAlreadyDefined` is raised when a piece of code (be it a module, or a script) attempts to execute two `class` statements that would produce classes that are impossible to distinguish between.

In the meantime, please see [here](https://neomodel.readthedocs.io/en/latest/extending.html#automatic-class-resolution)

**Comment by aanastasiou** [comment]
@mdelmans Any updates on this?

**Comment by mdelmans** [comment]
Thanks aanastasiou. Figured it out.
