### ISSUE TITLE
IntegerProperty default value

### ISSUE THREAD

**Issue by mdelmans** [neo4j-contrib/neomodel#433]
Hi,
I noticed when you set default value of IntegerProperty to be zero:

``` python
class Foo(StructuredNode)
    prop = IntegerProperty(default =0 )

foo = Foo()
foo.save()
>> {'id': 1}
```

works with `default = 1`:

``` python
class Foo(StructuredNode)
    prop = IntegerProperty(default =1 )

foo = Foo()
foo.save()
>> {'id': 1, 'prop' : 1}
```

**Comment by aanastasiou** [comment]
Literally just tried it verbatim in an iPython session and did not notice anything out of the ordinary.

![image](https://user-images.githubusercontent.com/1336337/56297659-a406b580-6128-11e9-9e53-f9f4ade6bf43.png)

Can you please let us know what is your `neomodel` version and possibly neo4j server version?
