### ISSUE TITLE
[Feature Suggestion] Get a result of a query as dict

### ISSUE THREAD

**Issue by sinwoobang** [neo4j-contrib/neomodel#434]
Hi. I'm so thankful for you who have been developing it.
I've been using this library to develop my project.

While I'm using this, I got a small idea of a feature.
It is that getting a result of a query as the type Dictionary.
I guess it can be added to the object `db`.

Would you let me your opinion of this?
Thank you.

**Comment by aanastasiou** [comment]
Thanks for the note. I do not think that this is the remit of `neomodel` however.

There is another module I am working on that offers this ability and a few other things. I will ping you a message when I make a release if that is any help.
