### ISSUE TITLE
ImportError: cannot import name 'Node'

### ISSUE THREAD

**Issue by anomit** [neo4j-contrib/neomodel#437]
I did a fresh install of neomodel in a new virtualenv.

On trying to run any basic test code, it throws up the usual stack trace every time:

```
File "/Users/anomit/workspace/blocksplit/backend/rest-flask.py", line 2, in <module>
    from neomodel import (StructuredNode, StringProperty, IntegerProperty, UniqueIdProperty, RelationshipTo, RelationshipFrom)
  File "/Users/anomit/.pyenv/versions/3.6.5/envs/testvenv/lib/python3.6/site-packages/neomodel/__init__.py", line 3, in <module>
    from .core import *
  File "/Users/anomit/.pyenv/versions/3.6.5/envs/testvenv/lib/python3.6/site-packages/neomodel/core.py", line 9, in <module>
    from neomodel.util import Database, classproperty, _UnsavedNode, _get_node_properties
  File "/Users/anomit/.pyenv/versions/3.6.5/envs/testvenv/lib/python3.6/site-packages/neomodel/util.py", line 8, in <module>
    from neo4j.v1 import GraphDatabase, basic_auth, CypherError, SessionError, Node
ImportError: cannot import name 'Node'
```

I did a check on the requirements in setup.py of neomodel. 
I notice that `neo4j-driver==1.7.2` is listed. And this confused me a bit once I did a pip show on the package.
`$ pip show neo4j-driver`
```
Name: neo4j-driver
Version: 1.6.3
Summary: Neo4j Bolt driver for Python
Home-page: https://github.com/neo4j/neo4j-python-driver
Author: Neo Technology
Author-email: drivers@neo4j.com
License: Apache License, Version 2.0
Location: /Users/anomit/.pyenv/versions/3.6.5/envs/testvenv/lib/python3.6/site-packages
Requires: neotime
```

I had already installed the `neo4j` official driver package earlier. The pip information for the same:
`$ pip show neo4j`
```
Name: neo4j
Version: 1.7.2
Summary: Neo4j Bolt driver for Python
Home-page: https://github.com/neo4j/neo4j-python-driver
Author: Neo Technology
Author-email: drivers@neo4j.com
License: Apache License, Version 2.0
Location: /Users/anomit/.pyenv/versions/3.6.5/envs/testvenv/lib/python3.6/site-packages
Requires: neobolt, neotime
```

The same summary description 🤷‍♂️ 

I did a reinstall on `neo4j-driver` to upgrade to 1.7.2 any way. I still keep getting the exception as noted in the beginning of this report. 

`$ pip uninstall neo4j-driver`
`$ pip install neo4j-driver==1.7.2`

```
Collecting neo4j-driver==1.7.2
  Downloading https://files.pythonhosted.org/packages/77/ac/b8b9dbe47062457ec9fa3f57b62198243869b33144218d40a03c7c25c170/neo4j-driver-1.7.2.tar.gz
Requirement already satisfied: neobolt<2,>=1.7.4 in /Users/anomit/.pyenv/versions/3.6.5/envs/testvenv/lib/python3.6/site-packages (from neo4j-driver==1.7.2)
Requirement already satisfied: neotime<2,>=1.7.1 in /Users/anomit/.pyenv/versions/3.6.5/envs/testvenv/lib/python3.6/site-packages (from neo4j-driver==1.7.2)
Requirement already satisfied: pytz in /Users/anomit/.pyenv/versions/3.6.5/envs/testvenv/lib/python3.6/site-packages (from neotime<2,>=1.7.1->neo4j-driver==1.7.2)
Requirement already satisfied: six in /Users/anomit/.pyenv/versions/3.6.5/envs/testvenv/lib/python3.6/site-packages (from neotime<2,>=1.7.1->neo4j-driver==1.7.2)
Installing collected packages: neo4j-driver
  Running setup.py install for neo4j-driver ... done
Successfully installed neo4j-driver-1.7.2
```

**Comment by anomit** [comment]
Here are the logs from the first time I ran pip install neomodel

```
pip install neomodel
Collecting neomodel
  Downloading https://files.pythonhosted.org/packages/5c/f5/0380fd6fde04be0a346584f395630c35b3185dbb456513a5e4e860ac046e/neomodel-3.3.1-py3-none-any.whl (69kB)
    100% |████████████████████████████████| 71kB 934kB/s
Requirement already satisfied: pytz>=2016.10 in /Users/anomit/.pyenv/versions/3.6.5/envs/testvenv/lib/python3.6/site-packages (from neomodel)
Collecting neo4j-driver<1.7.0,>=1.5.2 (from neomodel)
  Downloading https://files.pythonhosted.org/packages/12/db/1c68c1c244ea4afedf14459645a9c5e4124b9fbec12b2da02ed084ac32f7/neo4j-driver-1.6.3.tar.gz (188kB)
    100% |████████████████████████████████| 194kB 1.1MB/s
Requirement already satisfied: neotime<1.8,>=1.7.1 in /Users/anomit/.pyenv/versions/3.6.5/envs/testvenv/lib/python3.6/site-packages (from neo4j-driver<1.7.0,>=1.5.2->neomodel)
Requirement already satisfied: six in /Users/anomit/.pyenv/versions/3.6.5/envs/testvenv/lib/python3.6/site-packages (from neotime<1.8,>=1.7.1->neo4j-driver<1.7.0,>=1.5.2->neomodel)
Installing collected packages: neo4j-driver, neomodel
  Running setup.py install for neo4j-driver ... done
Successfully installed neo4j-driver-1.6.3 neomodel-3.3.1
```

**Comment by aanastasiou** [comment]
@anomit When you did the fresh install, did you do it via pip and pypi or pip and this repository?

At the moment, there are a few changes that have been merged in this repository that have not been pushed out as a release to pypi. One of these changes is the update of the driver to 1.7.2.

**Comment by anomit** [comment]
On Mon, Apr 22, 2019, 2:45 AM Athanasios Anastasiou <
notifications@github.com> wrote:

> @anomit <https://github.com/anomit> When you did the fresh install, did
> you do it via pip and pypi or pip and this repository?
>

Via pip and pypi. Do you suggest you pull the latest master to work with
the latest driver?

Also one of my original doubts stay, whats the functional difference
between the neo4j and neo4j-driver packages...

**Comment by anomit** [comment]
I had other code which was using the neo4j 1.7.2 API but for now I have downgraded to 1.6.3 and had to change import statements from `neo4j` to `neo4j.v1` . And for all practical purposes, it seems `neo4j` and `neo4j-driver` packages are idential.

This at least lets me write some abstracted code with neomodel.

Hope this doesn't break anything in the parts which use the native neo4j driver objects.

**Comment by John-Theo** [comment]
I encountered the same problem. Manually changed `from neo4j.v1 import` to `from neo4j import` fixed it. Works fine for me till now. 
I'm working with Python 3.7.2 on Windows, and packages `py2neo 4.2.0` / `neo4j 1.7.2` / `neo4j-driver 1.6.3` / `neomodel 3.3.1`. Hope it helps.

**Comment by aanastasiou** [comment]
@anomit & @John-Theo Thank you for bringing this to our attention, please see below.

>  Do you suggest [to] pull the latest master to work with the latest driver?

Yes, at the moment I would suggest that you do this. Changing the `neo4j-driver` version had been a long-standing request so after a [recent suggestion](https://github.com/neo4j-contrib/neomodel/issues/290), I went ahead and [accepted this particular change](https://github.com/neo4j-contrib/neomodel/pull/432) since the reasoning behind it was very well documented.

Before I do this, I run all tests locally, to what is now the current "master" and found no problems.

The only "problem" that I encountered was updating the code without "re-installing" it, which indicated a failure, similar to what you describe. Re-running `pip install -e ./` (within the `neomodel` folder that contains the `setup.py` file of course), fixed this "problem" in my case within a project that I use for development.

I have not however pushed a release (to pypi) because there are a few more modifications I wanted to add before making this a "release".

> one of my original doubts stay, what's the functional difference between the neo4j and neo4j-driver packages ?

I do not know. I have used the `neo4j-driver` package on its own very few times and consult it when I have to lookup data type implementation details. I have not had to lookup the `neo4j` package thus far.

All the best

**Comment by anomit** [comment]
@aanastasiou Thank you for your inputs and I really appreciate the hard work that has gone behind neomodel. It has made my code a lot cleaner and easier to extend. 

I shall be closing the issue as it's not really something that affects my codebase.

Cheers!
