### ISSUE TITLE
missing release notes

### ISSUE THREAD

**Issue by jberends** [neo4j-contrib/neomodel#450]
I really, really mis release notes of neomodel.

Neomodel is such a core to our framework that it is very hard to judge the changes in each release. furthermore we use https://pyup.io to maintain dependency tracking and notifications (with automatic PR and testing against source code) to understand changes in the dependency landscape. In this way we cannot judge was had been changed.

I can only assume many others are using neomodel in production environments and are dependent on proper release management with release notes.

Is there a way to add this in next releases. Especially with the upcoming py3 only release with a lot of backward incompatible changes (I suppose).

**Comment by aanastasiou** [comment]
@jberends In what other form than [the curret one](https://github.com/aanastasiou/neomodel/blob/pre-release_review/Changelog) would you expect this to be in?

**Comment by jberends** [comment]
ok.. i completely overlooked that. I was looking appearently at CAPITAL names eg. CHANGELOG. Sorry for that.

What I normally also look for in the 'releases' tab of github to inject the changelog in there in the release notes.

**Comment by aanastasiou** [comment]
@jberends No worries.

If that service can parse changelogs in somewhat more machine readable format to raise warnings / errors automatically, it might be worth reviewing the current log's format (?)

All the best
