### ISSUE TITLE
GraphQL Django integration

### ISSUE THREAD

**Issue by MardanovTimur** [neo4j-contrib/neomodel#453]
I customized the library **graphene-django** and now you can work with entities **StructuredNode**. The library supports filtering, sorting and pagination. Documentation in the manufacturing process, but already something is.
Try it out:
https://github.com/MardanovTimur/graphene-neo4j
Or (**neomodel-next** library installed (remove neomodel lib firstly))
```bash
pip install graphene-neo4j
```

**Comment by aanastasiou** [comment]
@MardanovTimur would it be possible to provide a clearer demonstration of how this applies to or affects the development of neomodel?

**Comment by MardanovTimur** [comment]
@aanastasiou, now, the main problem of neomodel library - how to interract data between the client and server. The popular server web-framework on python - Django. And the best structure of API in current time - GraphQL. For creating library graphene-neo4j, i created several usefull features and fixed common errors in neomodel library. The changes in neomodel-next (can i open the pull request from neomodel-next to this repo?) Sorry for my bad english

**Comment by aanastasiou** [comment]
@MardanovTimur no problem.

I think that it would be worth highlighting what are these features and common errors that have been addressed by your repository (?). Even in a simple text list form, it does not have to be detailed.
