### ISSUE TITLE
Optionally support double underscores within property names

### ISSUE THREAD

**Issue by mdw00d** [neo4j-contrib/neomodel#457]

**Comment by mdw00d** [comment]
Currently specifying property names that contain double underscores within the name are assumed to be filter expressions, where the "property" is split by the library into two parts, where the first part is taken to be the property name and the second part is taken to be a filter operator such as gt.

This unfortunately doesn't support property names that happen to contain double underscores within the name, such as is the case with property names automatically generated by the neosemantics library.

it would be useful to have some way to control this behavior.  Alternatively, perhaps this type of operation could be specified using a special character that is not legal within neo4j property names, as then there would be no chance of conflict.

**Comment by aanastasiou** [comment]
@mdw00d thanks for this note. At the moment [underscores are not a very good idea in general](https://neomodel.readthedocs.io/en/latest/properties.html#naming-convention).

Can you provide a very brief description of why does ``neosemantics`` work in this way? Does it allow for control over attribute names?

I wonder if there is an easier workaround for this...

All the best

**Comment by mdw00d** [comment]
The neosemantics library provides a way to import RDF into neo4j.   To accommodate RDF namespaces in an environment that doesn't support the colon character, neosemantics imports prefixed names by separating the prefix from the local portion of the name, e.g., foaf:Person becomes foaf__Person.   So the underscores are never at the beginning of the name but in the middle.

At the moment neosemantics does not allow one control over this behavior, although I did mention this issue to the maintainer.

**Comment by aanastasiou** [comment]
@mdw00d Sounds like there might be space for a "plugin" or tool that can handle this use case (?).

The schema could be incorporated into one word to the class using simple [camel case](https://en.wikipedia.org/wiki/Camel_case).

What do you think?

**Comment by mdw00d** [comment]
Are you suggesting that neosemantics should form the label by combining the namespace with the the local name using camel case?  While I am not a contributor to that project, I suppose they could do that, although that approach could raise other some issues.  The local name may or may not already start with a capital letter, and it is desirable to be able split the label back to get to the namespace and the local name with its original capitalization.  

The two libraries are associating their own unique uses for labels and the limited allowed characters in neo4j property labels makes collisions of this sort inevitable, I suppose.

**Comment by aanastasiou** [comment]
@mdw00d

Two things:

1. Neomodel can have [a property stored as an attribute under a different name at the backend](https://neomodel.readthedocs.io/en/latest/properties.html#independent-database-property-name)

2. If you now have another tool creating the graph schema and you want neomodel to interface with that schema then you need to somehow handle this translation, especially if the auto-generated attribute names don't follow convention. So, you could run this tool after neosemantics to take into account this attribute naming translation in automatically creating model classes for an RDF schema.

What do you think?

**Comment by aanastasiou** [comment]
@mdw00d Please let me know if this issue can be considered as resolved (?)

**Comment by mdw00d** [comment]
I was hoping for some mechanism so I would be able to use the neomodel and neosemantics libraries together, but I can continue to customize one or the other so they can coexist for now.  Thank you for your thoughts on this issue.

**Comment by aanastasiou** [comment]
@mdw00d No worries, did you try the differently named attribute / class attribute I am suggesting in an earlier message?
