### ISSUE TITLE
[QUESTION] unique values 

### ISSUE THREAD

**Issue by mpetyx** [neo4j-contrib/neomodel#46]
I would like to ask if there exists or if it could be possible to exist the unique entry of an entity in my database.
How could i avoid duplicates?

In django there exists :

class Meta:
        unique_together = (('attribute1', 'attribute2'), )

Is there anything similar in neomodel or could i just use that it should work?

**Comment by Enprogames** [comment]
Has this feature been implemented? I would love to use this in my projects.
