### ISSUE TITLE
Unique index properties should not be required

### ISSUE THREAD

**Issue by jonadaly** [neo4j-contrib/neomodel#468]
Note: this was previously raised as an issue #267 , but was closed - I believe in error. I would be happy for the original issue to be reopened and this one closed.

---

In neomodel, properties that are marked with `unique_index = True` are treated as required - attempting to deflate/inflate a node without this property set results in a `RequiredProperty` error.

This behaviour of neomodel directly contravenes the Neo4J documentation:

https://neo4j.com/docs/cypher-manual/current/schema/constraints/

> Unique property constraints ensure that property values are unique for all nodes with a specific label. Unique constraints do not mean that all nodes have to have a unique value for the properties — nodes without the property are not subject to this rule.

As was pointed out by @yarmash in the original issue, the solution is simple - remove the clause `or property.unique_index` in the `if` statement here:

https://github.com/neo4j-contrib/neomodel/blob/b843417bc9aa0568fc0612caa90597bff41d603e/neomodel/properties.py#L89

Happy to raise a PR for this change if that would be useful.

**Comment by aanastasiou** [comment]
#267 re-opened, please go ahead with the PR basing it on the latest version of `neomodel` from this repository.
