### ISSUE TITLE
Work with labels `SET` in neo4j

### ISSUE THREAD

**Issue by LayneSadler** [neo4j-contrib/neomodel#484]
EDIT: I want to be able to interact with nodes where I have `SET n:SomeLabel` using cypher. But the `_NODE_CLASS_REGISTRY` of neomodel errors when I try to do this because it's looking at Python classes for labels.

I'm trying to do this because to enable 'label propagation' for running graph algorithms on different groups of nodes because `cypher project` has not been working for me. 

How can I manually add neo4j labels to the class registry? Or skip it somehow.
https://neomodel.readthedocs.io/en/latest/module_documentation.html#neomodel.exceptions.ModelDefinitionMismatch

I have `Slice1` `Slice2` `Slice3` ... `Slice999` as labels on many classes of nodes. Kind of like a longitudinal label.

I've tried `a = MyNode.labels().append("SomeLabel"); a.save()` to no effect.
https://neomodel.readthedocs.io/en/latest/module_documentation.html#neomodel.core.StructuredNode.labels

I already use inheritance for sub-classes/sub-labels. That's not what this is about.

**Comment by HashRocketSyntax** [comment]
Honing in on this. I see the class at line 46 in util.py
https://github.com/neo4j-contrib/neomodel/blob/48ef1bc997090419e7678a452c6a107d2456f93e/neomodel/util.py

**Comment by HashRocketSyntax** [comment]
I was able to add entries to the `_NODE_CLASS_REGISTRY`
```
frozenset({'PRED0'}): neurography.models.Product,
 frozenset({'PRED1'}): neurography.models.Product,
 frozenset({'PRED2'}): neurography.models.Product}
```
But still ran into issues when I tried to call the node. 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.pyenv/versions/neurodb-py3.7/lib/python3.7/site-packages/neomodel/util.py in _object_resolution(self, result_list)
    165                     if type(a_result_attribute[1]) is Node:
--> 166                         resolved_object = self._NODE_CLASS_REGISTRY[frozenset(a_result_attribute[1].labels)].inflate(
    167                             a_result_attribute[1])

KeyError: frozenset({'Product', 'PRED0', 'ProductInput'})

...

TypeError: 'frozenset' object is not callable
```

**Comment by aanastasiou** [comment]
@HashRocketSyntax This would be impossible for the reasons detailed [here](https://github.com/neo4j-contrib/neomodel/pull/425).

A node's label has a very specific meaning in `neomodel`. What you would be trying to do cannot be done with `neomodel`, at least while trying to use labels.

Perhaps it can be done via attributes that can be indexed (?). Is it possible to describe this use case a little bit more please?
