### ISSUE TITLE
CypherSyntaxError

### ISSUE THREAD

**Issue by skandagnprodapt** [neo4j-contrib/neomodel#495]
Hi Guys, 

I get the following error when I try to execute a basic python script listed in neo4j documentation.

neobolt.exceptions.CypherSyntaxError: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead (line 1, column 16 (offset: 15))
"CREATE (n:Book {create_params}) RETURN n"

Using versions 

neo4j-driver                       1.7.2
neobolt                            1.7.16
neomodel                           3.3.2

Not working with neo4j 4.0

**Comment by KevinvOosterhout** [comment]
Hi @skandagnprodapt ,

This is known and reported in issue #487 They're currently working on a fix for this. If you'd like to use python with Neo4j i wold recommend sticking to Neo4j 3.5 as even the official neo4j drivers for 4.0 aren't released yet. This is expected in Q1/Q2 2020

**Comment by skandagnprodapt** [comment]
Thanks!
