### ISSUE TITLE
properties in StructuredNode can't have names like create, ... when calling save()

### ISSUE THREAD

**Issue by joeribelis** [neo4j-contrib/neomodel#500]
example

class Access(StructuredNode):
    uid = UniqueIdProperty()
    name = StringProperty(required=True)
    read = BooleanProperty()
    write = BooleanProperty()
    delete = BooleanProperty()
    create = BooleanProperty()

will give an TypeError: 'bool' object is not callable when calling save()

**Comment by HashRocketSyntax** [comment]
Downvote. Those should be "reserved words."
