### ISSUE TITLE
How to fetch all intermediate nodes between two Node sets programatically ?

### ISSUE THREAD

**Issue by sivachaitanya** [neo4j-contrib/neomodel#507]
I am trying the fetch all the intermediate Nodes and Relations between nodes A to D where actually graph is connected in A->B->D
without using cypherquery()

**Comment by aanastasiou** [comment]
This [might be possible](https://neomodel.readthedocs.io/en/latest/queries.html#node-sets-and-filtering) but it would be far quicker (and more flexible) to do it via a cypher query.
