### ISSUE TITLE
Neo4j 3.5 supported?

### ISSUE THREAD

**Issue by elferia** [neo4j-contrib/neomodel#508]
In README and [RTD](https://neomodel.readthedocs.io/en/latest/index.html), it is said that neomodel supports Neo4j 3.3 and below.
But [TravisCI](https://travis-ci.org/github/neo4j-contrib/neomodel/builds/591045481) shows that neomodel also support Neo4j 3.4.
Anyway, [they are end-of-support](https://neo4j.com/developer/kb/neo4j-supported-versions/).

I know that in #499 you are trying to support Neo4j 4.0. But 4.0 is not compatible with 3.x, so I need 3.5 support rather than 4.0.

According to [this article](https://neo4j.com/developer/kb/neo4j-supported-versions/), Neo4j 3.5 is compatible with driver 1.7.

https://github.com/neo4j-contrib/neomodel/blob/8d505e6d8716144fc51827bb80bab7ee6960835c/setup.py#L20

neomodel now depends on driver 1.7 so it seems that neomodel can support Neo4j 3.5. Or is it impossible for neomodel to support 3.5 due to difficult problems?  If so, when will they addressed?
I read https://github.com/neo4j-contrib/neomodel/wiki/TODOs-&-Enhancements , but I can't find about supporting latest versions.

**Comment by aanastasiou** [comment]
Thank you, it is now, please see latest version.
