### ISSUE TITLE
Getting Properties of Existing Relationships

### ISSUE THREAD

**Issue by egeucak** [neo4j-contrib/neomodel#515]
Hi, I have a question.

Let's say I have a model and a relationship as follows

```python
class CustomerRel(StructuredRel):
  products = ArrayProperty(StringProperty())

class Establishment(StructuredNode):
  name = StringProperty()
  customer = Relationship("Establishment", "SELLS_TO", model=CustomerRel)
```

When I filter establishments, I want to get their customers, and the products they sell to those customers. How can I get that? I couldn't figure out how to get properties of relationships

**Comment by aanastasiou** [comment]
Please see [here](https://neomodel.readthedocs.io/en/latest/queries.html#node-sets-and-filtering) and maybe let us know if this refers to something different (?)
