### ISSUE TITLE
Adding support for retry_on_session_expire or max_connection_lifetime

### ISSUE THREAD

**Issue by vato20071** [neo4j-contrib/neomodel#518]
The issue is that GCE closes idle connections after some time. So, if the connection is closed, queries fail and therefore requests don't pass with the error:
`Failed to read from defunct connection Address(host='example.app', port=7688) (Address(host='example_address', port=7688))`

There is a parameter specified in `neomodel/util.py:184`
```
    @ensure_connection
    def cypher_query(self, query, params=None, handle_unique=True, retry_on_session_expire=False, resolve_objects=False):`
```
But I wasn't able to find the configuration parameter for this option.

Also, the same issue can be fixed by settings connection lifetime to be less than idle connection timeout in GCE. This could be done by settings `max_connection_lifetime` when initiating driver as specified in 
https://github.com/neo4j/neo4j-python-driver/issues/316
But no configuration option for this parameter as well.

I could initiate driver with this configuration option and set `neomodel.db.driver` object myself, but that would be a last resort. If there's any better solution, please feel free to suggest.

It would be good to add either MAX_CONNECTION_LIFETIME to neomodel_config or RETRY_ON_SESSION_EXPIRE as a config when initiating driver in `db.set_connection`. Also, it probably would be best if `Database.set_connection` accepted `**kwargs` and passed it down to `GraphDatabase.driver` object.

I'm using
- neo4j 3.5.16 inside docker
- nginx to reverse proxy inside docker
- `neo4j-driver==1.7.2`
- `neobolt==1.7.17`
- `neomodel==3.3.2`
- `neotime==1.7.4`

**Comment by aanastasiou** [comment]
Thank you, two things:

1. Can you please update to the latest version (4.0.0 of neomodel) 
2. Just to be clear, what you are proposing is to make the existing time-out property a setting and allow neomodel to pick it up as the default when it is set in the config (?)
