### ISSUE TITLE
neomodel 4.0.0 depends on Django 1.11.29

### ISSUE THREAD

**Issue by gs00cut** [neo4j-contrib/neomodel#520]
Hello,

I need to move to neo4j 4.x for my project. For that, I would like to install the latest neomodel release 4.0.0.
My project uses Django 3.0.4 along with the Django Rest Framework (3.11.0).

I can't do the neomodel upgrade as version 4.0.0 seem to require Django version 1.11.29 (see [`setup.py`](https://github.com/neo4j-contrib/neomodel/blob/4.0.0/setup.py)).

Is it normal that it requires such an old version of Django?

Thanks,

Gilles

**Comment by whatSocks** [comment]
Hi, we are dealing with this issue in this PR:
https://github.com/neo4j-contrib/neomodel/pull/519 

Can you check if that works for you? Goal is to have it merged tomorrow (sept 24)

**Comment by gs00cut** [comment]
Hi,

I have installed neomodel version 4.0.1 and everything is working fine so far.
Thanks !

Gilles
