### ISSUE TITLE
Issue with : python manage.py install_labels

### ISSUE THREAD

**Issue by KevinRodrigues05** [neo4j-contrib/neomodel#524]
I'm completely new to neo4j and django and im trying to connect the both with neomodel.
I'm following the neomodel documentation and I'm facing this issue :
```
$ python manage.py install_labels
Unknown command: 'install_labels'
Type 'manage.py help' for usage.
```
Could someone please help me out with this?

**Comment by gitkp11** [comment]
same here. Couldnt figure it out how to work on this. Is install_labels valid in python-3.7 with django-2?

**Comment by gitkp11** [comment]
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    ...
    'django_neomodel',
    ...
]

make sure to add 'django_neomodel' in installed_apps. also add it before your user apps.

**Comment by KevinRodrigues05** [comment]
Thank you @gitkp11 that worked fr me as well.
