### ISSUE TITLE
ImportError: cannot import name '__'

### ISSUE THREAD

**Issue by sangee14** [neo4j-contrib/neomodel#527]
I have got the error saying ``` ImportError: cannot import name '__' ``` when trying to import using ``` from pypher import __ ```

first I got ModuleNotFoundError: No module named 'pypher' even though its already installed, 

somehow I resolved the error, but now I am getting the **ImportError**

Python 3.6
Rasa 2.0
OS: Ubuntu 20.04

**Comment by aanastasiou** [comment]
I am afraid I cannot help with this, `pypher` is an excellent module but as far as I am aware, `neomodel` does not use it.

All the best
