### ISSUE TITLE
Fetch by Neo4j internal id (<id>)

### ISSUE THREAD

**Issue by KevinRodrigues05** [neo4j-contrib/neomodel#531]
How can i fetch a node by using the neo4j internal id created automatically when we create the node?

`node = Person.nodes.get(id=23) `

throws an exception : **ValueError: No such property id on Function**

Could someone please help me how to resolve this??
@aanastasiou

**Comment by dnarvaez27** [comment]
This has been my approach to retrieve a node by its ID
```
def get_one(id):
    try:
        model = NodeModel(id=id)
        model.refresh()
        return model
    except NodeModel.DoesNotExist:
        return None
```

Where `NodeModel` is any subclass of `StructuredNode`

by `refresh`ing the node, it access to the neo4j DB to get the node that matches its current properties

**Comment by KevinRodrigues05** [comment]
> This has been my approach to retrieve a node by its ID
> 
> ```
> def get_one(id):
>     try:
>         model = NodeModel(id=id)
>         model.refresh()
>         return model
>     except NodeModel.DoesNotExist:
>         return None
> ```
> 
> Where `NodeModel` is any subclass of `StructuredNode`
> 
> by `refresh`ing the node, it access to the neo4j DB to get the node that matches the properties of the class node

**Comment by KevinRodrigues05** [comment]
@dnarvaez27 Thank you for replying but this doesn't seem to be working because the exception is raised when `Neomodel(id=id)` is called. hence it doesn't refresh.

**Comment by KevinRodrigues05** [comment]
Thank you @dnarvaez27 it worked.
