### ISSUE TITLE
Calling install_all_labels twice fails 

### ISSUE THREAD

**Issue by mjmare** [neo4j-contrib/neomodel#539]
Neomodel 4.0.1, python 3.9.1 on macOS 11.1

Calling install_all_labels for a second time fails with an exception: 
```
neo4j.exceptions.ClientError: {code: Neo.ClientError.Schema.EquivalentSchemaRuleAlreadyExists} {message: An equivalent constraint already exists, 'Constraint( id=2, name='constraint_6e016ec3', type='UNIQUENESS', schema=(:Address {uuid}), ownedIndex=1 )'.}
```

Cause: in core.py lines 113 and 127 there is a test to catch this exception:
```
 if str(e).lower().startswith("an equivalent constraint already exists"):
```
This should be:
```
 if str(e.message).lower().startswith("an equivalent constraint already exists"):
```

**Comment by melwil** [comment]
I think this issue is still in there.

Essentially I can't update my neo4j schema without emptying the whole db, which isn't feasible in production. I'm not sure I agree on the enhancement tag, this looks like a bug to me, and until it's fixed you can't really use the command on an existing db.

A quick fix for this issue would be much appreciated.

**Comment by mjmare** [comment]
Still not fixed in 4.0.3 unfortunately. Why? I gave the solution when raising the issue.

**Comment by leogout** [comment]
Hi, I am facing the same issue as of today with the latest version (3.3.2)

**Comment by leogout** [comment]
```
Found website.neomodels.Country                                                            
 + Creating unique constraint for code on label Country for class website.neomodels.Country
Traceback (most recent call last):
  File "\venv\Scripts\neomodel_install_labels", line 67, in <module>              
    main()                                                                                                            
  File "\venv\Scripts\neomodel_install_labels", line 64, in main                  
    install_all_labels()                                                                                              
  File "\venv\lib\site-packages\neomodel\core.py", line 125, in install_all_labels
    install_labels(cls, quiet=False, stdout=stdout)                                                                   
  File "\venv\lib\site-packages\neomodel\core.py", line 100, in install_labels    
    db.cypher_query("CREATE CONSTRAINT "                                                                              
  File "\venv\lib\site-packages\neomodel\util.py", line 33, in wrapper            
    return func(self, *args, **kwargs)                                                                                
  File "\venv\lib\site-packages\neomodel\util.py", line 229, in cypher_query      
    raise exc_info[1].with_traceback(exc_info[2])                                                                     
  File "\venv\lib\site-packages\neomodel\util.py", line 212, in cypher_query      
    response = session.run(query, params)                                                                             
  File "\venv\lib\site-packages\neo4j\__init__.py", line 492, in run              
    self._connection.fetch()                                                                                          
  File "\venv\lib\site-packages\neobolt\direct.py", line 419, in fetch
    return self._fetch()
  File "\venv\lib\site-packages\neobolt\direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "\venv\lib\site-packages\neobolt\direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.ClientError: An equivalent constraint already exists, 'Constraint( id=4, name='constraint_ccaf2229', type='UNIQUENESS', schema=(:Country {code}), ownedIndex=3 )'.
```

**Comment by fadesibert** [comment]
> ```
> Found website.neomodels.Country                                                            
>  + Creating unique constraint for code on label Country for class website.neomodels.Country
> Traceback (most recent call last):
>   File "\venv\Scripts\neomodel_install_labels", line 67, in <module>              
>     main()                                                                                                            
>   File "\venv\Scripts\neomodel_install_labels", line 64, in main                  
>     install_all_labels()                                                                                              
>   File "\venv\lib\site-packages\neomodel\core.py", line 125, in install_all_labels
>     install_labels(cls, quiet=False, stdout=stdout)                                                                   
>   File "\venv\lib\site-packages\neomodel\core.py", line 100, in install_labels    
>     db.cypher_query("CREATE CONSTRAINT "                                                                              
>   File "\venv\lib\site-packages\neomodel\util.py", line 33, in wrapper            
>     return func(self, *args, **kwargs)                                                                                
>   File "\venv\lib\site-packages\neomodel\util.py", line 229, in cypher_query      
>     raise exc_info[1].with_traceback(exc_info[2])                                                                     
>   File "\venv\lib\site-packages\neomodel\util.py", line 212, in cypher_query      
>     response = session.run(query, params)                                                                             
>   File "\venv\lib\site-packages\neo4j\__init__.py", line 492, in run              
>     self._connection.fetch()                                                                                          
>   File "\venv\lib\site-packages\neobolt\direct.py", line 419, in fetch
>     return self._fetch()
>   File "\venv\lib\site-packages\neobolt\direct.py", line 461, in _fetch
>     response.on_failure(summary_metadata or {})
>   File "\venv\lib\site-packages\neobolt\direct.py", line 755, in on_failure
>     raise CypherError.hydrate(**metadata)
> neobolt.exceptions.ClientError: An equivalent constraint already exists, 'Constraint( id=4, name='constraint_ccaf2229', type='UNIQUENESS', schema=(:Country {code}), ownedIndex=3 )'.
> ```

I don't think this is the latest version (should be >= 4.x) - you have 3.3

**Comment by aanastasiou** [comment]
@fadesibert It probably would have been at the time the post was made.
