### ISSUE TITLE
Specify neo4j database name in connection string

### ISSUE THREAD

**Issue by locorecto** [neo4j-contrib/neomodel#541]
In the documentation I see it's possible to connect specify the neo4j connection string using the following statement:

```python
from neomodel import config
config.DATABASE_URL = 'bolt://neo4j:neo4j@localhost:7687'
```

On neo4j 4.1, I am using multiple databases under the same server. I would like to specify the database I am using either in the connection string or somewhere else.

In py2neo I can do something like this:
```python
graph = Graph(host='localhost', port=7687, auth=('neo4j','pwd'), name='dbname')
```

Is there any way to do this in neomodel?

**Comment by aanastasiou** [comment]
@locorecto At the moment, changing the database would have to be done via a USE query which can be sent via a `cypher_query` from within neomodel. Hope this helps but please let me now either way.

**Comment by locorecto** [comment]
Thanks for the response. I will give it a try and let you know.

**Comment by robobenklein** [comment]
My personal opinion here would be to turn this into a feature request for adding the database name to neomodel's config settings.

How difficult might that be?

**Comment by jtommi** [comment]
@aanastasiou I tried 
`results, meta = db.cypher_query(":use neo4j")` which fails with a syntax error
and
`results, meta = db.cypher_query("use neo4j")` which fails by saying that a return or update statement is required.

So for me this workaround didn't work. @locorecto did it work for you?

**Comment by mariusconjeaud** [comment]
As of neomodel version 4.0.10, the following works for me : `config.DATABASE_URL = 'bolt://neo4j:neo4j@localhost:7687/mydatabase'`
