### ISSUE TITLE
Relationship Definition has no "connect" method

### ISSUE THREAD

**Issue by np6hd** [neo4j-contrib/neomodel#546]
![image](https://user-images.githubusercontent.com/44717536/106078167-eff9d300-60e0-11eb-9535-57af9911ffbd.png)

**Comment by np6hd** [comment]
UPDATE:
![image](https://user-images.githubusercontent.com/44717536/106412344-8b5ab300-6415-11eb-9f0b-294408e08262.png)
I dynamically allow for creating a field for Person object and using the build manager of the Relationship Definition class I was finally about to turn that field into a Relationship Manger class.

**Comment by np6hd** [comment]
Issue still persists that relationship itself is not fully accessible after program ends and restarts.

**Comment by skyleronken** [comment]
Same issue. Im trying to access objects referenced via relationship (in the same way as done in the tutorial), but the RelationshipDefinition object doesnt behave as it should.
