### ISSUE TITLE
Aggragation and Annotation

### ISSUE THREAD

**Issue by likecodingloveproblems** [neo4j-contrib/neomodel#549]
django QuerySet has aggregate and annotation methods. But in [neomodel.nodes](https://github.com/neo4j-contrib/neomodel/blob/bfeae3e10498006dc0aae6bab2885a3c0f194dc3/neomodel/match.py#L565) this methods are not implemented. as i study neo4j has some [aggregation functions](https://neo4j.com/docs/cypher-manual/current/functions/aggregating/). what's reason?

**Comment by mariusconjeaud** [comment]
@tonioo does that sound like what we discussed where we would like to make the fetch_relations more Django-like with methods like Optional(), Collect(), etc... ?

**Comment by tonioo** [comment]
@mariusconjeaud Yes, definitely. I really think that's something we should invest time on.

**Comment by mariusconjeaud** [comment]
See releases 5.4.x
