### ISSUE TITLE
[Support Neo4j 4.3] Neo4j 4.3: list index out of range in drop_indexes

### ISSUE THREAD

**Issue by mdantonio** [neo4j-contrib/neomodel#567]
After upgrading to neo4j 4.3 I'm experiencing the following error when executing remove_all_labels()

```
File "/usr/local/lib/python3.9/dist-packages/neomodel/core.py", line 81, in remove_all_labels
  drop_indexes(quiet=False, stdout=stdout)
File "/usr/local/lib/python3.9/dist-packages/neomodel/core.py", line 62, in drop_indexes
  index[7][0], index[8][0]))
IndexError: list index out of range
```

Is neomodel intended to be compatible with neo4j 4.3? From the tests it seems that it is only tested up to to neo4j 4.1

**Comment by mdantonio** [comment]
After some more inspection, this problem seems to be related to the introduction of token lookup indexes, that is a new index type introduced in neo4j 4.3
https://neo4j.com/docs/operations-manual/current/performance/index-configuration/#index-configuration-token-lookup

These indexes are created by default in neo4j and available even on a freshly created graph:

```
[1, 'index_343aff4e', 'ONLINE', 100.0, 'NONUNIQUE', 'LOOKUP', 'NODE', [], [], 'token-lookup-1.0']
[2, 'index_f7700477', 'ONLINE', 100.0, 'NONUNIQUE', 'LOOKUP', 'RELATIONSHIP', [], [], 'token-lookup-1.0']
```

remove_all_labels fails when executed on a empty database, i.e. when ONLY these indexes are available... maybe that they should be skipped because can't / shouldn't be removed

**Comment by whatSocks** [comment]
Related https://github.com/neo4j-contrib/django-neomodel/issues/62

**Comment by mdantonio** [comment]
Hello,
I would like to ask if there are some updates here, since all linked issues and pulled requests seem to be closed / merged

**Comment by anatoly-scherbakov** [comment]
Does not reproduce for me anymore with `neomodel==4.0.8`.

**Comment by mdantonio** [comment]
Can't say the same, for me the problem is still there with 4.0.8 :disappointed:

**Comment by anatoly-scherbakov** [comment]
@mdantonio I am very new to Neo4j I must admit but perhaps it depends on the system version? I have tested on 4.1.9 and on 4.4.2, good on both.

**Comment by mdantonio** [comment]
I'm on neo4j 4.4.2 too (the dockerized version)

**Comment by a-takahashi223** [comment]
You can reproduce by running following commands:

```
NEO4J_VERSIONS="4.3" PYTHON_VERSIONS="3.8" ./tests-with-docker-compose.sh
```

**Comment by mariusconjeaud** [comment]
I am currently working on updating neomodel to (at least) Neo4j version 4.4 (See #653). I also fixed this, and extended it to fix test_drop_labels in a clearer way (specifically excluding the default LOOKUP indexes).
So I will include your changes in that PR.
