### ISSUE TITLE
How to compare local and remote node while skipping the id property ?

### ISSUE THREAD

**Issue by Wenzel** [neo4j-contrib/neomodel#577]
Hi,

first thank you for neomodel, I'm testing this library since 2 days now, and so far you have a better documentation than py2neo, I was up and running in no time.

I started to integrate neomodel with my test suite, to replace some dirty cypher queries.

I'm at this point where I'm creating a whole tree of nodes, and in my test I'd like to assert that the tree is the one I expect, by comparing with a local one:
~~~Python
class Tree(StructuredNode):
    name = StringProperty(required=True)
    children_tree = RelationshipTo('Tree', 'HAS_CHILD_TREE')
    children_leaf = RelationshipTo('Leaf', 'HAS_CHILD_LEAF')


# empty tree with no children
EXPECT_TREE_01 = Tree(name="tree01")

def test_tree_01():
    # create the trees in the DB
    # xxxxx
    # get the remote tree
    remote_tree = Tree.nodes.get(name="tree01")
    # compare
    assert remote_tree == EXPECT_TREE_01
~~~

However, pytest raises an AssertionError, since the `id` property is missing from the local tree:

~~~
E       AssertionError: assert <Tree: {'name......', 'id': 14}> == <Tree: {'name......'}>
E         +<Tree: {'name': 'tree01', 'id': 14}>
E         -<Tree: {'name': 'tree01'}>
~~~

Any idea how to compare these 2 nodes while skipping the id property ?

Note: the whole idea here is to compare 2 subgraphs with a single `assert ==` statement

Thanks !

**Comment by Wenzel** [comment]
I've just realized that it wasn't possible to build a local neomodel subgraph, as connecting 2 nodes raises a ValueError:
~~~python3
ValueError: Tree.children_leaf.connect() attempted on unsaved node
~~~

Any comment on this feature ?

**Comment by AntonLydike** [comment]
> I've just realized that it wasn't possible to build a local neomodel subgraph, as connecting 2 nodes raises a ValueError:

Since `children_leaf.connect()` will be saved to the database immediately, it can only be called on nodes that are already present in the database. I don't think I fully understand your use case though, why do you want to replicate the tree locally? I am afraid that neomodel cannot handle that at the moment. 

> the whole idea here is to compare 2 subgraphs with a single assert == statement

I think you'd have to write that logic yourself for your loop-free special case...
