### ISSUE TITLE
lazy param causes get() to return not the node but ID only

### ISSUE THREAD

**Issue by ralfeus** [neo4j-contrib/neomodel#584]
When `get(lazy=False)` or `get_or_none(lazy=False)` are run the node object is returned. However when `get(lazy=True)` is run only ID of the object is returned. 
I assumed `lazy=True` would still return the object but without properties populated.

**Comment by chamounestro** [comment]
Hello, this is the documented behavior of the lazy kwarg: https://neomodel.readthedocs.io/en/latest/getting_started.html#retrieving-nodes

**Comment by aanastasiou** [comment]
I would second @chamounestro response. This is the intended behaviour of `lazy`. Would it be possible for you to provide some more information as to why you feel there should be something wrong with this behaviour? Returning an *"object without properties populated"* would not make sense as the result of a `get()` function. You can always instantiate a "fresh" object which will not have its properties populated, or, you can take the returned `id` and ask neomodel to return the actual Python object based on the data it retrieves from the database.
