### ISSUE TITLE
Bug: install_labels breaks when updating neo4j from 4.3 to 4.4

### ISSUE THREAD

**Issue by alessandromarchetti** [neo4j-contrib/neomodel#595]
## What happened
There is a subtle yet highly impacting issue related to a Neo4J breaking change from v4.3 to v4.4.
In particular we are using Neo4J Aura, so we don't have control on the updates, and our neomodel backed API stopped working all of a sudden without any code or library change. We saw it rasing a `ClientError` at startup while installing labels, so having labels being installed at startup brought it down with dockers not starting anymore.

## The issue
To illustrate the issue I'll focus on constraints (we were having issues with UniqueConstraints) but the same should apply to indexes as well.
The issue is that the `install_labels` funtion ignores just one kind of exception, specifically [this one](https://github.com/neo4j/neo4j/blob/4fe5e8b568b8f399193e2c8e74e56f8fb17ca82a/community/community-it/kernel-it/src/test/java/org/neo4j/graphdb/SchemaAcceptanceTest.java#L263) which has status code `Neo.ClientError.Schema.EquivalentSchemaRuleAlreadyExists`, while it raises [this other one](https://github.com/neo4j/neo4j/blob/4fe5e8b568b8f399193e2c8e74e56f8fb17ca82a/community/community-it/kernel-it/src/test/java/org/neo4j/graphdb/SchemaAcceptanceTest.java#L317) which has status code `Neo.ClientError.Schema.ConstraintAlreadyExists`. (Official Neo4j status codes can be found [here](https://neo4j.com/docs/status-codes/4.3/))

The difference between the two exceptions, as deducted from the tests in the two links above, is the following: 
- `Neo.ClientError.Schema.EquivalentSchemaRuleAlreadyExists` is raised when a constraint is created with same characteristics and same name
- `Neo.ClientError.Schema.ConstraintAlreadyExists` is raised when a constraint is created with same characteristics but different name.

Although the indexes and contraints are created in neomodel with no explicit naming, neo4j tries to create them with a deterministic name generated by a [specific name generation function](https://github.com/neo4j/neo4j/blob/1403c9d2396c3009958d017b3d24640b6d220e2e/community/schema/src/main/java/org/neo4j/internal/schema/SchemaRule.java#L82) and then fails with the according exception.

The issue lies in the fact that the name generation function has changed for the [4.3 version](https://github.com/neo4j/neo4j/blob/1403c9d2396c3009958d017b3d24640b6d220e2e/community/schema/src/main/java/org/neo4j/internal/schema/SchemaRule.java#L82) to the [4.4 version](https://github.com/neo4j/neo4j/blob/4b0714552461b6a96b9821cca374be86e028c8af/community/schema/src/main/java/org/neo4j/internal/schema/SchemaNameUtil.java#L79) so while trying to install already existing labels after the update neo4j will generate different names and trigger the second kind of exception, which is raised by neomodel.

## Steps to reproduce
1. Install labels
2. Update neo4j to 4.4
3. Install same labels

##  Solution
The solution is to consider neo4j's auto-generated names as subject to change and catch both types of exceptions in order to ensure compatibility for the upgrade of an existing database to 4.4 as well as any future updates that might change neo4j's name generation function. The PR is #596 

For anyone that might experience this the easy temporary fix is to call the function to install labels explicitely and catch the raised exception there, same as in the linked PR.

**Comment by AntonLydike** [comment]
Closed as PR is merged
