### ISSUE TITLE
Querying relationships: Filter on direction

### ISSUE THREAD

**Issue by olarcher** [neo4j-contrib/neomodel#599]
From the docs I understand that a Relationship can be directed or undirected, depending on how I want to query the data. Let's say I have a simple user model, with a relationship called "LIKES":

```
class User(StructuredNode):
    name = StringProperty(required=True)
    likes = Relationship('User', 'LIKES')
``` 

Given `A-[LIKES]->B` `A-[LIKES]->C` , `B-[LIKES]->D` and `D-[LIKES]->A`, I want to know: 
- Which users does A like? [B,C]
- Who likes A? [D]
- Who likes or is liked by A? [B,C,D]

1. Is it correct to define `likes` as a `Relationship`, or should I use `RelationshipTo`?
2. How can I query the db to get the infos above? Can I somehow filter the call to `likes` based on relationship direction? Do I need to define a `Traversal`? ...?

Thanks!

**Comment by a-takahashi223** [comment]
```python
class User(StructuredNode):
    name = StringProperty(required=True)
    likes = RelationshipTo('User', 'LIKES')
    liked_by = RelationshipFrom('User', 'LIKES')


a = User.nodes.get(name="A")
a.likes  # Which users does A like?
a.liked_by  # Who likes A?
chain(a.liked_by, a.likes)  # Who likes or is liked by A?
```

**Comment by ibury08** [comment]
@a-takahashi223 could I request further clarification on this pattern? In the case where I have two classes with a bi-directional relationship, how can I fetch all Users from Client A and all Clients from User B?

The docs state: "When the relationship can be bi-directional, please avoid establishing two complementary RelationshipTo, RelationshipFrom relationships and use Relationship, on one of the class definitions instead."

```
class User(StructuredNode):
    name = StringProperty(required=True)

class Client(StructuredNode):
    name = StringProperty(required=True)
    users = Relationship(User, 'WORKS_WITH')
```

I can retrieve all Users via:
```
a = Client.nodes.get(name="A")
a.users.all()
```
However, it's not clear from the docs how to retrieve the other direction (i.e. all clients for a given user).
