### ISSUE TITLE
Pull request #592 cause an error in case of relationship inharitance 

### ISSUE THREAD

**Issue by olegchigirin** [neo4j-contrib/neomodel#600]
Approved pull request #592 is not a minor change. For it makes our application completely impossible to start.

In <4.0.8 release, such code was valid:

```
class RelA(StructuredRel):
    some_property = 'some value'

class ModelA(StructuredNode):
     rel_a: neomodel.ZeroOrMore = RelationshipTo('ModelA', 'REL_TYPE_A', model=RelA)
     rel_b: neomodel.ZeroOrMore = RelationshipTo('ModelA', 'REL_TYPE_B', model=RelA)                                                           
```

It is useful when describing different relationships with the same relationship logic.

After the 4.0.8 release, such relationship definitions raise exceptions:

`Relationship of type REL_TYPE_B redefined as <class 'RelA'>`

This is not a minor code update, and in our case, it requires refactoring at least half of the relationship definitions.

**Update:**

I investigate what is going on. The problem above is not a correct explanation of the error I got in my project. The real issue is the following:

Let us have relationship classes with the following inheritance

```
class Class1(StructuredRel):
    pass


class SubClass1(Class1):
    pass


class SubClass2(Class1):
    pass
```

And following model class:

```
class RelationshipDefiner(StructuredNode):
    rel_1 = Relationship('RelationshipDefiner', 'SOME_REL_LABEL', model=Class1)
    rel_2 = Relationship('RelationshipDefiner', 'SOME_REL_LABEL', model=SubClass1)
    rel_3 = Relationship('RelationshipDefiner', 'SOME_REL_LABEL', model=SubClass2)
```

We get the following error:

```
neomodel.exceptions.RelationshipClassRedefined: Relationship of type SOME_REL_LABEL redefined as <class 'SubClass1'>.
RelationshipDefiner --> <class 'RelationshipDefiner'>
SOME_REL_LABEL --> <class 'SubClass1'>
```

The correct behavior is to allow both of them to use 'SOME_REL_LABEL' because they extend the same base class.

Error is coming from here:

https://github.com/neo4j-contrib/neomodel/blob/2850013f01f5c51ef19fc43323fed8aecb97090c/neomodel/relationship_manager.py#L378

```
if not issubclass(model, db._NODE_CLASS_REGISTRY[label_set]):
    raise RelationshipClassRedefined(relation_type, db._NODE_CLASS_REGISTRY, model)
else:
    db._NODE_CLASS_REGISTRY[label_set] = model
```
Because we replace the previous mentioning in case the next one is the subclass of the first one.

I see the correct approach of this: 

We have to store in _NODE_CLASS_REGISTRY the most parent class from all extended types, described this relationship. In my case, we have to keep Class1.

**Update 2**:

```
class RelationshipDefiner(StructuredNode):
    rel_2 = Relationship('RelationshipDefiner', 'SOME_REL_LABEL', model=SubClass1)
    rel_3 = Relationship('RelationshipDefiner', 'SOME_REL_LABEL', model=SubClass2)
    rel_1 = Relationship('RelationshipDefiner', 'SOME_REL_LABEL', model=Class1)
```

An additional case is this one. When the parent class is not the first one, and the first two classes using 'SOME_REL_LABEL' are on the same level in the hierarchy, we got a RelationshipClassRedefined error on trying to process rel_3.

**Comment by whatSocks** [comment]
hi @olegchigirin, thank you for your detailed explanation and apologies for causing this trouble. Will look into this next week.

**Comment by whatSocks** [comment]
@olegchigirin - still working on it but is priority

**Comment by nossila** [comment]
@olegchigirin please take a look at my current solution https://github.com/neo4j-contrib/neomodel/pull/604

**Comment by olegchigirin** [comment]
@nossila, it looks great!
