### ISSUE TITLE
.filter not utilizing available neo4j indexes for text search like icontains?

### ISSUE THREAD

**Issue by somejonus** [neo4j-contrib/neomodel#615]
I have 2 separate indexes available for 1 label (text) with 1 property (title) of my DB Version 4.4.3. One is type TEXT, the other is type FULLTEXT. When using .filter(title__icontains='contains text'), judging by the performance compared against a respective cypher query, neither index seems to be utilized.

Is this expected and if so, is there a way to force the utilization of an index? I did not find anything regarding the usage of indexes in the documentation.

**Comment by mariusconjeaud** [comment]
So I ran this test inside the test_match_api tests : `Coffee.nodes.filter(name__icontains="cap")`

And I ran the query that was generated in PROFILE mode, and as you can see, it does run a NodeIndexSeek => indexes are used.

<img width="972" alt="image" src="https://github.com/neo4j-contrib/neomodel/assets/7679761/4be7e8b7-0ea6-466f-8109-883ce0733319">

So I think you are facing a different problem and you should look at the queries log, identify which one takes a long time, then check the profile.
