### ISSUE TITLE
Add support for bearer_auth (sso)

### ISSUE THREAD

**Issue by lqst** [neo4j-contrib/neomodel#617]
It looks like neomodel only supports basic_auth. Need support for bearer_auth for sso.

**Comment by mariusconjeaud** [comment]
This should be pretty easy to implement.

The trick (for me) will be setting up test, especially for the Integration tests pipeline. Do you have something already ? Note : today, the Integration tests pipeline spins up a default Neo4j docker image ; maybe we could have one with SSO enabled ? Then the test gets a token and tries to connect and that should be it.

What do you think @lqst ?

**Comment by mariusconjeaud** [comment]
See PR #744 => this allows to pass your own driver => you can create it any way you want, including with SSO token instead of basic auth.
