### ISSUE TITLE
Installation failure of current release

### ISSUE THREAD

**Issue by pithhelmet8669** [neo4j-contrib/neomodel#622]
Trying to install

`C:\Users\tallman>pip install neomodel
Collecting neomodel
  Using cached neomodel-4.0.8-py3-none-any.whl (46 kB)
Requirement already satisfied: pytz>=2021.1 in c:\python310\lib\site-packages (from neomodel) (2022.1)
Collecting neo4j-driver==4.3.6
  Using cached neo4j-driver-4.3.6.tar.gz (76 kB)
  Preparing metadata (setup.py) ... done
Collecting neobolt==1.7.17
  Using cached neobolt-1.7.17.tar.gz (183 kB)
  Preparing metadata (setup.py) ... done
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting Shapely==1.7.1
  Using cached Shapely-1.7.1.tar.gz (383 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\tallman\AppData\Local\Temp\pip-install-ak2bmkgf\shapely_ff497deb39d3472bbd98f5c1f977459c\setup.py", line 85, in <module>
          from shapely._buildcfg import geos_version_string, geos_version, \
        File "C:\Users\tallman\AppData\Local\Temp\pip-install-ak2bmkgf\shapely_ff497deb39d3472bbd98f5c1f977459c\shapely\_buildcfg.py", line 205, in <module>
          lgeos = CDLL("geos_c.dll")
        File "C:\Python310\lib\ctypes\__init__.py", line 374, in __init__
          self._handle = _dlopen(self._name, mode)
      FileNotFoundError: Could not find module 'geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

`

I am open to ideas why it is failing.

**Comment by pithhelmet8669** [comment]
One note...   the shapely install of version 
Shapely 1.8.1.post1
installed fine - solo

**Comment by alimcmaster1** [comment]
Hi - this was fixed in https://github.com/neo4j-contrib/neomodel/pull/612 which will be included in the next release.

Shapely required libgeos try something like:
`apt-get install -y libgeos-dev`

Feel free to reopen if needed
