### ISSUE TITLE
migrate to travis-ci.com

### ISSUE THREAD

**Issue by a-takahashi223** [neo4j-contrib/neomodel#627]
[travis-ci.org shut down on May 31, 2021](https://blog.travis-ci.com/2021-05-07-orgshutdown). So since then CI tests for this repository is never done. [The latest test is done on June 3, 2021](https://travis-ci.org/github/neo4j-contrib/neomodel).
The migration to travis-ci.com is needed.

The migration is easy but only neo4j-contrib members (perhaps admins) can do it.
Please migrate to travis-ci.com and restart CI tests.

**Comment by a-takahashi223** [comment]
Hi,

How about this issue?

**Comment by a-takahashi223** [comment]
Hi,

Don't you think that CI tests are necessary?
Or do CI tests run on the service other than Travis CI?

**Comment by mariusconjeaud** [comment]
Created GitHub Actions workflow for integration tests and publishing to PyPI on GitHub release.

Will also need to add documentation upload to readthedocs but closing this issue.
