### ISSUE TITLE
Neo4j query across multiple databases

### ISSUE THREAD

**Issue by mephoenix** [neo4j-contrib/neomodel#628]
Hi, 

Is there an example of a complex query that spans across multiple databases? (Using Neo4j fabric)

Examples of such queries can be found here ->
https://www.markhneedham.com/blog/2020/02/03/neo4j-cross-database-querying-fabric/

Thanks,
Vinod

**Comment by AntonLydike** [comment]
Such a feature is currently not on the roadmap, so we'll close this issue. A complete roadmap will be released soon.
