### ISSUE TITLE
Min Shapely version must be set to 1.8.1 not 1.7.1 for Neomodel to install on Windows 10 or default Heroku, Django deploy

### ISSUE THREAD

**Issue by enjoysmath** [neo4j-contrib/neomodel#630]
I couldn't dev on this laptop, what I did to fix it was fork this repo, change in `setup.py` the Shapely >=1.7.1 to >=1.8.1, which for some reason turns out to be the one pip wants to install when I do `pip install -r requirements.txt` and `neomodel` is listed on a line.

So please fix this, because now it's also broken when I deploy on Heroku and it tries to build everything per requirements.txt.

**Comment by olegchigirin** [comment]
https://github.com/neo4j-contrib/neomodel/pull/612

It seems like this is already provided in the master branch, but there is not releases with this fix

**Comment by mariusconjeaud** [comment]
Included in release 4.0.10
