### ISSUE TITLE
Achieve parity of `StructuredNode.cypher` and `db.cypher_query`

### ISSUE THREAD

**Issue by AntonLydike** [neo4j-contrib/neomodel#633]
I noticed that `StructuredNode.cypher` is missing the `resolve_objects` argument. I looked around and found no reason why it should be missing. While adding support for it, I noticed that there are quite a few more flags on `db.cypher_query` that are not available for `StructuredNode.cypher`. Are there any reasons for that?

I am specifically talking about:

 - `handle_unique` Whether or not to raise UniqueProperty exception on Cypher's ConstraintValidation errors
 - `retry_on_session_expire` Whether or not to attempt the same query again if the transaction has expired

**Comment by aanastasiou** [comment]
Hello @AntonLydike `db.cypher_query()` is what every other component uses to actually communicate with the DBMS.

A trivial example is using that function to return "raw" results as opossed to resolved objects (e.g, imagine a query that returns raw strings and integers that cannot be resolved to any of the classes in a given hierarchy). The various parameters of `db.cypher_query()` are there to serve different purposes depending on where that function is called from.

`StructuredNode.cypher()` also ultimately calls `db.cypher_query()` but in turn, it is called from operations that don't really need to return classes (or at least, did not, at the time it was created). For example, when updating a `StructuredNode`, all we need are the node's properties (which are returned in the driver's object) to update a specific `StructuredNode` attributes.

Was there a particular use case you had in mind when proposing these changes?

**Comment by mariusconjeaud** [comment]
Closing for cleaning the Issues log and Thanos' answer looks OK to me. Feel free to re-open if you had a specific use case in mind requiring changes.
