### ISSUE TITLE
4.0.9 release

### ISSUE THREAD

**Issue by olegchigirin** [neo4j-contrib/neomodel#643]
Question only.

In the master branch there are several major and important updates, that are not yet released:

https://github.com/neo4j-contrib/neomodel/pull/604
https://github.com/neo4j-contrib/neomodel/pull/607
https://github.com/neo4j-contrib/neomodel/pull/601

And several more.

When we can expect the release of a new version of neomodel?

**Comment by mariusconjeaud** [comment]
Duplicate of #653

**Comment by mariusconjeaud** [comment]
Closing to group all discussions about the evolution of neomodel in #653
