### ISSUE TITLE
Shapely1.7.1 does not exist for neomodel 4.0.8

### ISSUE THREAD

**Issue by jordanscience** [neo4j-contrib/neomodel#645]
Hey,

When I want to install the last version of neomodel ( 4.0.8 ) , I get the following error. 

ERROR: Could not find a version that satisfies the requirement Shapely==1.7.1 (from versions: 1.0a7, 1.0b1, 1.0b2, 1.0b3, 1.0b4, 1.0rc1, 1.0rc2, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.2b1, 1.2b2, 1.2b3, 1.2b4, 1.2b5, 1.2b6, 1.2b7, 1.2rc1, 1.2rc2, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.2.10, 1.2.12, 1.2.13, 1.2.14, 1.2.15, 1.2.16, 1.2.17, 1.2.18, 1.2.19, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.5.13, 1.5.14, 1.5.15, 1.5.16, 1.5.17, 1.6a1, 1.6a2, 1.6b1, 1.6b2, 1.6b3, 1.6b4, 1.6b5, 1.6.0, 1.6.1, 1.6.2, 1.6.2.post1, 1.6.3, 1.6.4, 1.6.4.post1, 1.6.4.post2, 1.7a1, 1.7a2, 1.7a3, 1.7b1, 1.7.0, 1.7.1, 1.8a1, 1.8a2, 1.8a3, 1.8rc1, 1.8rc2, 1.8.0, 1.8.1, 1.8.1.post1, 1.8.2, 1.8.3, 1.8.4, 2.0a1)

I fixed it manually by downloading the tar gz and modify inside it the setup.py 

Jordan

**Comment by olegchigirin** [comment]
@jordanscience 

Which version of python do you use?

https://github.com/cchangelabs/neomodel/releases/tag/3.3.4

Fix of this is already in master branch, you can use our .whl package if you want:

https://github.com/cchangelabs/neomodel/releases/tag/3.3.4
