### ISSUE TITLE
Neo4j v5 support

### ISSUE THREAD

**Issue by alexresolute** [neo4j-contrib/neomodel#650]
Hi, is there any estimate on when neo4j v5 will be supported? After attempting to upgrade, the first incompatibility I found was in the syntax used to created indexes.

**Comment by mariusconjeaud** [comment]
Hello,

Please read here #653.

FYI, I got 4.4 to work, and 5.x is mostly working in my dev environment - and yes, the syntax for indexes changed so the game will be to find a way to support both 4 (at least 4.4) and 5 at the same time.
I will be investigating this once I get a new release in for 4.4

**Comment by mariusconjeaud** [comment]
Duplicate of #653

**Comment by mariusconjeaud** [comment]
Closing to group all discussions about the evolution of neomodel in #653
