### ISSUE TITLE
[Python support] Python 3.10

### ISSUE THREAD

**Issue by mariusconjeaud** [neo4j-contrib/neomodel#660]

**Comment by olegchigirin** [comment]
As a comment:

In our project, using a shapely hot fix, we upgraded our code base to python 3.11. So it seems if the project supports python 3.10, it might support 3.11 also

**Comment by mariusconjeaud** [comment]
@olegchigirin can you share the hotfix you mentioned ? Or maybe even create a PR for it ?

**Comment by mariusconjeaud** [comment]
Fixed in #661

**Comment by mariusconjeaud** [comment]
Included in release 4.0.9

**Comment by olegchigirin** [comment]
> @olegchigirin can you share the hotfix you mentioned ? Or maybe even create a PR for it ?

https://github.com/neo4j-contrib/neomodel/pull/612

I meant that update of the Shapely version. With this pull request, our project is running well using python 3.11
