### ISSUE TITLE
Invalid constraint syntax, ON and ASSERT should not be used.

### ISSUE THREAD

**Issue by hamashoool** [neo4j-contrib/neomodel#666]
## Expected Behavior (Mandatory)
when you run the command to install labels. It was supposed to create them.

## Actual Behavior (Mandatory)
But it will return this error. 
The error message you  suggests that the syntax you used to create the constraint is no longer valid in the version of Neo4j 5. The ON and ASSERT keywords were used in older versions of Neo4j to create constraints, but they have since been replaced by FOR and REQUIRE.

## How to Reproduce the Problem
just use Neo4j 5 and current neomodel

### Simple Example
I was using django_neomodel, when I create the models.py. I was supposed to run the install_labels command. So, when I ran the command I got the error.

## Screenshots (where it's possibile)
![Screenshot from 2023-02-14 21-04-02](https://user-images.githubusercontent.com/54283482/218908660-cc785d1b-6941-4636-8a01-f72e922c62f0.png)

Currently used versions
neo4j 5.4.0
django_neomodel 0.0.7
current version of neomodel

### Versions

  - OS:
  - Library:
  - Neo4j:

**Comment by mariusconjeaud** [comment]
This made me realize I hadn't opened a Pull Request yet for my upgrade to Neo4j v5. I did it just now, check out : #668

**Comment by mariusconjeaud** [comment]
FYI, I am just waiting to be able to make a release out of my latest PR (which adds support for Neo4j up to version 4.4) before merging the 5.x PR. That way we'll have a last release that supports 3.5 -> 4.x ; and then we can extend to 5.x (and it will still support 4.4 LTS)
