### ISSUE TITLE
Automatic inflation of Path nodes returned by cypher query

### ISSUE THREAD

**Issue by 73VW** [neo4j-contrib/neomodel#715]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. 
Before sending unsolicited pull requests, please open a feature request to discuss your proposal.

If you have questions on usage, please ask on [the Discussion Forum](https://community.neo4j.com) instead of creating an issue here.

## Feature description (Mandatory)

Hello everyone, 

It seems that nodes contained in a path are not inflated when using `resolve_objects=True` in `db.cypher_query`.

Checking in the code seems to confirm that. [This method](https://github.com/neo4j-contrib/neomodel/blob/master/neomodel/util.py#L208) seems to inflate `Node`, `Relationship` or iterate over a `list` but doesn't do anything regarding `Path` objects returned by a cypher query.

My concern is that I make a query to find all nodes at a depth X from a certain center node. 

``` py
        ....
        query = f"""
    MATCH (p) WHERE id(p) = {center}
    MATCH path = (p)-[r:links*1..{depth}]-(connected)
    RETURN path
"""
        results, meta = db.cypher_query(query, resolve_objects=True)
        ...
```

This returns a list of `Path` objects.

## Considered alternatives

Iteratively inflate all nodes of a path.

## How this feature can improve the project?

This will resolve nodes of a path under the hood.

**Comment by aanastasiou** [comment]
Indeed. These features have been developed and merged at different time scales, hence these discrepancies. Thanks for flagging this up.

**Comment by mariusconjeaud** [comment]
Part of release 5.1.1
