### ISSUE TITLE
version numbering of neomodel and its corresponding neo4j driver is confusing

### ISSUE THREAD

**Issue by jeromecc** [neo4j-contrib/neomodel#719]
Hello guys!

Thanks for the hard work. I just wanted to let you know that for someone who very recently entered the neo4j space, it is extremely confusing that neomodel Version 5.0.1 2023-06 is using neo4j-driver==4.4.10. I guess I just spent the day scratching my head, wondering why neomodel wouldn't connect to my database (neo4j 5.9) whereas the latest neo4j Python driver was working just fine.

Thanks.

jérôme

**Comment by jeromecc** [comment]
Turned out my bug may be related to a redefinition of config ```from neomodel import config``` to ```config = AutoConfig(...)``` in the settings.py file of my Django project.

**Comment by aanastasiou** [comment]
@jeromecc Thanks for letting us know. Good luck with your project.
