### ISSUE TITLE
Refactor independent `db` functions into `Database`

### ISSUE THREAD

**Issue by aanastasiou** [neo4j-contrib/neomodel#739]
## Feature description (Mandatory)

A number of functions in `neomodel/core.py` and `neomodel/util.py` take a `db` argument whether explicitly, or implicitly (i.e. take `db` from the global context).

These can be refactored under the `Database` class.

This will result in better code organisation and it will also avoid circular import issues that appear at the moment when [working on more advanced features](https://github.com/neo4j-contrib/neomodel/pull/738/commits/e155d93c770894850a166ce4c9a5363a9d13a052#diff-5a14848686f658a9fab17bad447b0d3631c13d078bd3bbde13804138e3150e24R308).

However, this will also have *a relatively large impact on tests and possibly user code*, so it has to be scheduled for release appropriately.

**Comment by mariusconjeaud** [comment]
Done as part of the async refactoring, with former independent db functions marked as deprecated. To be removed in next major release (6+)
