### ISSUE TITLE
Support for Vector indexes

### ISSUE THREAD

**Issue by mariusconjeaud** [neo4j-contrib/neomodel#756]
Neo4j added a new type of index in version 5.11 : [Vector index](https://neo4j.com/docs/cypher-manual/current/indexes-for-vector-search/)

It comes with a set of commands to query it.

But it is still in beta mode, so the set of commands are subject to change, so I suggest we hold off a bit before adding support for this new index type ; but happy to debate.

**Comment by CyrusOfEden** [comment]
I might just take a stab at this over the holidays. Any tips?

**Comment by mariusconjeaud** [comment]
So, the `_install_node` / `_install_relationship` are the ones where the magic happens (if a node has an `index` property, it will create an index.

A few tricks here though :
- We must pass an extra property to mention the type of index we want to create (so we create a vector and not the default range index)
- We must check that the Neo4j version is right to create vector indexes. There are utility methods and examples for this, like : `if self.version_is_higher_than("5.7")`

An underlying question is that we should provide a way to make neomodel query using vector indexes, since it's a specific syntax in Cypher (something like `CALL db.index.vector.queryNodes`) and returns a list of elements with a similarity score. So that would require a separate method I guess ?
