### ISSUE TITLE
Autocomplete not recognizing parameters of an instance of "StructuredNode".

### ISSUE THREAD

**Issue by SandeshGowda-0094** [neo4j-contrib/neomodel#757]
## Description

When using Neomodel with certain IDEs (e.g., VSCode), autocomplete for dynamically defined properties within a class that inherits from `StructuredNode` is not working as expected. This issue affects the developer experience when creating instances of the class with property assignments.

## Code Example

```python
from neomodel import StructuredNode, StringProperty

class Person(StructuredNode):
    self.name = StringProperty(default=name)

# Autocomplete not recognizing 'name' in the following instance creation:
sam = Person(name='sam')

```
I found a way, but it's not convinient...
```python
from neomodel import StructuredNode, StringProperty

class Person(StructuredNode):
    def __init__(self, name=None, **kwargs):
        super(Person, self).__init__(**kwargs)
        self.name = StringProperty(default=name)

# Autocomplete can now recognize when used a constructor
sam = Person(name='sam')

```
## Expected Behavior
Autocomplete should recognize the dynamically defined property name during the creation of an instance, providing suggestions as the developer types.

I would really appreciate if any would address this issue..
it would mean a lot to developer's experience.

**Comment by mariusconjeaud** [comment]
Thanks for your issue. 

FYI, GitHub Copilot does propose properties for autocompletion in this scenario. I know it's not exactly what you're asking, but at least it is one solution :-)

<img width="417" alt="image" src="https://github.com/neo4j-contrib/neomodel/assets/7679761/1254d811-cad0-46b0-a94f-686a8cca6a77">
