### ISSUE TITLE
neomodel_inspect_database - Only writes first relationship

### ISSUE THREAD

**Issue by schlopmyflop** [neo4j-contrib/neomodel#781]
## Expected Behavior
neomodel_inspect_database writes all relationships to StructuredNode

## Actual Behavior
neomodel_inspect_database only writes first relationship to StructuredNode

## How to Reproduce the Problem
create node with 2 different outgoing relationship types

### Simple Example

```cypher
create (p1:Person)
create (p2:Person)
create (p3:Pet)
create (p1)-[:HAS_FRIEND]->(p2)
create (p1)-[:HAS_PET]->(p3)
```
run neomodel_inspect_database script

```bash
neomodel_inspect_database --db bolt://neo4j:neo4j@localhost:7687 --write-to output.py
```

output:
```python
from neomodel import StructuredNode, RelationshipTo, StructuredRel, ZeroOrOne

class Person(StructuredNode):
    has_friend = RelationshipTo("Person", "HAS_FRIEND", cardinality=ZeroOrOne)
```

expected output (which can be replicated by removing the limit clause in RelationshipInspector.outgoing_relationships):

```python
from neomodel import StructuredNode, RelationshipTo, StructuredRel, ZeroOrOne

class Person(StructuredNode):
    has_friend = RelationshipTo("Person", "HAS_FRIEND", cardinality=ZeroOrOne)
    has_pet = RelationshipTo("Pet", "HAS_PET", cardinality=ZeroOrOne)
```

### Cause
the LIMIT clause in RelationshipInspector.outgoing_relationships causes only the first relationship to be returned:
https://github.com/neo4j-contrib/neomodel/blob/4bd630261647d1f32f387c413dc57555a3106e2c/neomodel/scripts/neomodel_inspect_database.py#L119-L136

### Versions

  - OS: Windows 11
  - Library: 5.2.1
  - Neo4j: 5.12.0

**Comment by mariusconjeaud** [comment]
Hey ! Now that neomodel 5.3.0 is out and work on async is done ; I hope I can soon have a look into that !

Thank you for the nicely documented issue :)

**Comment by mariusconjeaud** [comment]
@schlopmyflop Fixed in the attached PR, should make it into 5.3.1
