### ISSUE TITLE
Missing import in contrib __init__

### ISSUE THREAD

**Issue by tobiascaliskan** [neo4j-contrib/neomodel#785]
## Expected Behavior (Mandatory)
Being able to import the **Spatial_properties** within the folder **contrib**.

## Actual Behavior (Mandatory)
Currently only the SemiStructuredNode can be imported.

## How to Reproduce the Problem
1. Create a new file
2. Try to import the PointProperty using **from neomodel.contrib.spatial_properties import PointProperty"

I managed to solve the issue by adding the import within the __init__.py file for the properties in the contrib.__init__.py file

## Specifications (Mandatory)

Currently used versions
5.2.1

**Comment by mariusconjeaud** [comment]
This works for me : `from neomodel.contrib.spatial_properties import PointProperty`

So do you mean you would want to do : `from neomodel import PointProperty` ? Or `from neomodel.contrib import PointProperty`?
