### ISSUE TITLE
Neomodel trying to connect to localhost, even if the database is on Aura ( When calling NODE_NAME.nodes.all() )

### ISSUE THREAD

**Issue by tseren1218** [neo4j-contrib/neomodel#787]
## Expected Behavior (Mandatory)
NODE_NAME.nodes.all returning all the nodes

## Actual Behavior (Mandatory)
Couldn't connect to localhost:7687 (resolved to ()):
Failed to establish connection to ResolvedIPv6Address(('::1', 7687, 0, 0)) (reason [WinError 10061] No connection could be made because the target machine actively refused it)
Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 7687)) (reason [WinError 10061] No connection could be made because the target machine actively refused it)

## How to Reproduce the Problem
Create a form class. Inside that, try to call NODE_NAME.nodes.all():

class ConnectedLocationsForm(forms.Form):
     connected_locations: Location.nodes.all()
     # Any statement
      . . . . . 
 
### Simple Example
Create a form class. Inside that, try to call NODE_NAME.nodes.all():

class ConnectedLocationsForm(forms.Form):
     connected_locations: Location.nodes.all()
     # Any statement
      . . . . . 

Datasets and Statements

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Windows 11
  - Library: django_neomodel 0.1.1, neomodel 5.1.2
  - Neo4j: 5.12.0

**Comment by curious-broccoli** [comment]
you should probably share what you set your config to:
```
from neomodel import config
config.DATABASE_URL = 'bolt://neo4j:neo4j@localhost:7687'
```

**Comment by mariusconjeaud** [comment]
I agree please share how you initiate the connection, either through `config.DATABASE_URL`, or `db.set_connection`
