### ISSUE TITLE
zero or more relationships in either direction of type RELATIONSHIP_NAME on node (4:2c06737f-f675-4209-a253-42d649d5fc59:395) of class 'NODE_LABEL'

### ISSUE THREAD

**Issue by tseren1218** [neo4j-contrib/neomodel#792]
## Expected Behavior (Mandatory)
Successfully accessing relationship from node class object (either StructuredNode or DjangoNode)

## Actual Behavior (Mandatory)
When accessing node's relationship from the node class object (either StructuredNode or DjangoNode), neomodel doesn't seem to recognize an existing relationship, even though there clearly is a relationship between the nodes when querying Neo4j Aura.
The error says:
zero or more relationships in either direction of type RELATIONSHIP_NAME on node (4:2c06737f-f675-4209-a253-42d649d5fc59:395) of class 'NODE_LABEL'

## How to Reproduce the Problem
Create simple child node class and make a relationship with it's parent node class. And try to access parent node from the child class

### Simple Example
class City(StructuredNode):
     name=StringProperty()
     state=RelationshipTo('State', 'IS_IN')

class State(StructuredNode):
     name=StringProperty()
     cities=RelationshipTo('City', 'HAS')

city = City.nodes.get(name='New York')
# Where error occurs
print(city.state)

Datasets and Statements

## Specifications (Mandatory)
python-3.10
neomodel-latest

Currently used versions

### Versions

  - OS: Windows 11
  - Library: 
  - Neo4j:

**Comment by demattosanthony** [comment]
@tseren1218 did you find a solution to this? Im having the same issue
