### ISSUE TITLE
Cannot get derived models working properly

### ISSUE THREAD

**Issue by arsham** [neo4j-contrib/neomodel#96]
Hi,

In following example:

```
class Person(StructuredNode):
    pass

class DerivedPerson(Person):
    friend = RelationshipTo('DerivedPerson', 'FRIEND')
```

When I instantiate from DerivedPerson and try to connect to another node, but it says 
`AttributeError: 'RelationshipDefinition' object has no attribute 'connect'`

DerivedPerson.index.get() says : 

`DoesNotExist: Can't find node in index matching query`
It's on neomodel/index.py line 57

Although I fixed it by adding this line at the bottom of my model ( not a good fix ):
`DerivedPerson.index.get = Person.index.get`

**Comment by PiotrKurnik** [comment]
Similar problem here. What is it that I am doing wrong: 

`class Book(StructuredNode):
    author = StringProperty(required=True)
    title = StringProperty(required=True)
    description = StringProperty()
    tags = RelationshipTo('Tag', 'HAS_TAG')

    def __init__(self, author, title, description):
        self.author = author
        self.title = title
        self.description = description
    def add_tags(self, tag_name):
        b = Tag.find_by_name(tag_name)
        if b:
            self.tags.connect(b)
        else:
            new = Tag(name=tag_name)
            new.save()
            self.tags.connect(new)
    @classmethod
    def find_book_by_author(cls, author):
        return cls.nodes.get(author=author)


class Tag(StructuredNode):
    name = StringProperty(required=True, unique_index=True)
    book = RelationshipFrom('Book', 'HAS_TAG')
    @classmethod
    def find_by_name(cls, name):
        try:
            return cls.nodes.get(name=name)
        except cls.DoesNotExist:
            return None

`
then:
`b1 = Book(author='a', title='t', description='d')
b1.save()
<Book: {'description': 'd', 'title': 't', 'id': 331, 'author': 'a', }>
b1.add_tags('d')
`
